[package]
name = "vx-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
vx-core = { workspace = true }
vx-content = { workspace = true }
glam = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
rodio = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
