//! Play phase messages for active in-game communication, chunk streaming, and player replication.

use std::sync::Arc;
use telos_core::coords::ChunkPos;
use telos_voxel::{
    chunk::ChunkSnapshot,
    light::{ChunkLight, LIGHT_LAYER_BYTES, LightLayer},
    occupancy::Occupancy,
    state::BlockStateId,
    storage::{Blocks, Packed},
};

use crate::bounded::{BoundedString, BoundedVec};
use crate::error::{ProtocolError, Result};
use crate::varint::{
    decode_varint, decode_varlong, encode_varint, encode_varlong, unzigzag_i32, zigzag_i32,
};

/// Client responds to server heartbeat challenge to measure RTT.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sKeepAlive {
    /// Opaque challenge ID matching server's keep-alive request.
    pub id: u64,
}

impl C2sKeepAlive {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varlong(cursor)?;
        Ok(Self { id })
    }
}

/// Server issues periodic heartbeat challenge to detect stale connections and measure latency.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cKeepAlive {
    /// Opaque challenge ID generated by server.
    pub id: u64,
}

impl S2cKeepAlive {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varlong(cursor)?;
        Ok(Self { id })
    }
}

/// Client sends chat message or command string to server.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C2sChatMessage {
    /// Message or command payload (max 256 bytes).
    pub message: BoundedString<256>,
}

impl C2sChatMessage {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.message.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let message = BoundedString::<256>::decode(cursor)?;
        Ok(Self { message })
    }
}

/// Server broadcasts formatted chat message or system alert to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cChatMessage {
    /// Sender name or `"[Server]"` prefix.
    pub sender: BoundedString<32>,
    /// Formatted chat message payload.
    pub message: BoundedString<256>,
    /// Millisecond Unix epoch timestamp when message was accepted.
    pub timestamp: u64,
}

impl S2cChatMessage {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.sender.encode(buf);
        self.message.encode(buf);
        encode_varlong(self.timestamp, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sender = BoundedString::<32>::decode(cursor)?;
        let message = BoundedString::<256>::decode(cursor)?;
        let timestamp = decode_varlong(cursor)?;
        Ok(Self {
            sender,
            message,
            timestamp,
        })
    }
}

/// Client notifies server of updated player position and view angles.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct C2sPlayerPosition {
    /// Player world X coordinate.
    pub x: f64,
    /// Player world Y coordinate.
    pub y: f64,
    /// Player world Z coordinate.
    pub z: f64,
    /// Player camera yaw in degrees.
    pub yaw: f32,
    /// Player camera pitch in degrees.
    pub pitch: f32,
    /// Whether player is currently touching ground.
    pub on_ground: bool,
}

impl Eq for C2sPlayerPosition {}

impl C2sPlayerPosition {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&self.x.to_le_bytes());
        buf.extend_from_slice(&self.y.to_le_bytes());
        buf.extend_from_slice(&self.z.to_le_bytes());
        buf.extend_from_slice(&self.yaw.to_le_bytes());
        buf.extend_from_slice(&self.pitch.to_le_bytes());
        buf.push(u8::from(self.on_ground));
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.len() < 33 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let x = f64::from_le_bytes(cursor[0..8].try_into().unwrap());
        let y = f64::from_le_bytes(cursor[8..16].try_into().unwrap());
        let z = f64::from_le_bytes(cursor[16..24].try_into().unwrap());
        let yaw = f32::from_le_bytes(cursor[24..28].try_into().unwrap());
        let pitch = f32::from_le_bytes(cursor[28..32].try_into().unwrap());
        let on_ground = cursor[32] != 0;
        *cursor = &cursor[33..];

        if !x.is_finite() || !y.is_finite() || !z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "position",
                reason: "Coordinates must be finite numbers".to_string(),
            });
        }
        if !yaw.is_finite() || !pitch.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "orientation",
                reason: "Orientation angles must be finite numbers".to_string(),
            });
        }
        if x.abs() > 30_000_000.0 || z.abs() > 30_000_000.0 || !(-2000.0..=5000.0).contains(&y) {
            return Err(ProtocolError::InvalidValue {
                field: "position",
                reason: "Coordinates out of valid world bounds".to_string(),
            });
        }
        if !(-95.0..=95.0).contains(&pitch) {
            return Err(ProtocolError::InvalidValue {
                field: "pitch",
                reason: format!("Pitch angle {pitch} out of valid [-90, 90] range"),
            });
        }

        Ok(Self {
            x,
            y,
            z,
            yaw,
            pitch,
            on_ground,
        })
    }
}

/// Server sends game join confirmation and initial spawn configuration.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cJoinGame {
    /// Server-assigned player entity ID.
    pub entity_id: u32,
    /// Initial spawn position X.
    pub spawn_x: f64,
    /// Initial spawn position Y.
    pub spawn_y: f64,
    /// Initial spawn position Z.
    pub spawn_z: f64,
    /// Server-enforced view distance in chunks.
    pub view_distance: u32,
}

impl Eq for S2cJoinGame {}

impl S2cJoinGame {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.entity_id, buf);
        buf.extend_from_slice(&self.spawn_x.to_le_bytes());
        buf.extend_from_slice(&self.spawn_y.to_le_bytes());
        buf.extend_from_slice(&self.spawn_z.to_le_bytes());
        encode_varint(self.view_distance, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let entity_id = decode_varint(cursor)?;
        if cursor.len() < 24 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let spawn_x = f64::from_le_bytes(cursor[0..8].try_into().unwrap());
        let spawn_y = f64::from_le_bytes(cursor[8..16].try_into().unwrap());
        let spawn_z = f64::from_le_bytes(cursor[16..24].try_into().unwrap());
        *cursor = &cursor[24..];
        let view_distance = decode_varint(cursor)?;

        if !spawn_x.is_finite() || !spawn_y.is_finite() || !spawn_z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "spawn_pos",
                reason: "Spawn coordinates must be finite numbers".to_string(),
            });
        }
        if !(1..=128).contains(&view_distance) {
            return Err(ProtocolError::InvalidValue {
                field: "view_distance",
                reason: format!("View distance {view_distance} out of valid 1..=128 range"),
            });
        }

        Ok(Self {
            entity_id,
            spawn_x,
            spawn_y,
            spawn_z,
            view_distance,
        })
    }
}

/// Serializes an in-memory `ChunkSnapshot` into a compact wire byte representation.
pub fn encode_chunk_snapshot(snapshot: &ChunkSnapshot, buf: &mut Vec<u8>) {
    // 1. Version tag
    buf.push(1);

    // 2. Blocks
    match snapshot.blocks() {
        Blocks::Uniform(state) => {
            buf.push(0);
            encode_varint(state.0, buf);
        }
        Blocks::Packed(packed) => {
            buf.push(1);
            buf.push(packed.log2());
            let palette = packed.palette();
            encode_varint(palette.len() as u32, buf);
            for s in palette {
                encode_varint(s.0, buf);
            }
            let words = packed.words();
            encode_varint(words.len() as u32, buf);
            for w in words {
                buf.extend_from_slice(&w.to_le_bytes());
            }
        }
    }

    // 3. Occupancy
    match snapshot.blocks() {
        Blocks::Uniform(_) => {
            let is_solid = snapshot.occupancy().col_y[0] != 0;
            buf.push(u8::from(is_solid));
        }
        Blocks::Packed(_) => {
            for col in snapshot.occupancy().col_y.iter() {
                buf.extend_from_slice(&col.to_le_bytes());
            }
            for col in snapshot.occupancy().col_x.iter() {
                buf.extend_from_slice(&col.to_le_bytes());
            }
            for col in snapshot.occupancy().col_z.iter() {
                buf.extend_from_slice(&col.to_le_bytes());
            }
        }
    }

    // 4. Light
    if let Some(light) = snapshot.light() {
        buf.push(1);
        match &light.sky {
            LightLayer::Uniform(val) => {
                buf.push(0);
                buf.push(*val);
            }
            LightLayer::Nibbles(bytes) => {
                buf.push(1);
                buf.extend_from_slice(&**bytes);
            }
        }
        match &light.block {
            LightLayer::Uniform(val) => {
                buf.push(0);
                buf.push(*val);
            }
            LightLayer::Nibbles(bytes) => {
                buf.push(1);
                buf.extend_from_slice(&**bytes);
            }
        }
    } else {
        buf.push(0);
    }
}

/// Deserializes a `ChunkSnapshot` from a wire byte slice.
#[allow(clippy::too_many_lines, clippy::similar_names)]
pub fn decode_chunk_snapshot(pos: ChunkPos, cursor: &mut &[u8]) -> Result<ChunkSnapshot> {
    if cursor.is_empty() {
        return Err(ProtocolError::UnexpectedEof);
    }
    let version = cursor[0];
    *cursor = &cursor[1..];
    if version != 1 {
        return Err(ProtocolError::Malformed(format!(
            "Unsupported chunk snapshot codec version: {version}"
        )));
    }

    // Blocks
    if cursor.is_empty() {
        return Err(ProtocolError::UnexpectedEof);
    }
    let blocks_tag = cursor[0];
    *cursor = &cursor[1..];

    let (blocks, is_uniform) = match blocks_tag {
        0 => {
            let state_id = decode_varint(cursor)?;
            (Blocks::Uniform(BlockStateId(state_id)), true)
        }
        1 => {
            if cursor.is_empty() {
                return Err(ProtocolError::UnexpectedEof);
            }
            let log2 = cursor[0];
            *cursor = &cursor[1..];
            if log2 > 4 {
                return Err(ProtocolError::Malformed(format!(
                    "Invalid log2 bit width: {log2}"
                )));
            }

            let palette_len = decode_varint(cursor)? as usize;
            let mut palette = Vec::with_capacity(palette_len);
            for _ in 0..palette_len {
                let id = decode_varint(cursor)?;
                palette.push(BlockStateId(id));
            }

            let words_len = decode_varint(cursor)? as usize;
            let expected_words = 512usize << log2;
            if words_len != expected_words {
                return Err(ProtocolError::Malformed(format!(
                    "Words length mismatch: got {words_len}, expected {expected_words}"
                )));
            }

            let required_bytes = words_len * 8;
            if cursor.len() < required_bytes {
                return Err(ProtocolError::UnexpectedEof);
            }

            let mut words = Vec::with_capacity(words_len);
            for _ in 0..words_len {
                let w = u64::from_le_bytes(cursor[..8].try_into().unwrap());
                *cursor = &cursor[8..];
                words.push(w);
            }

            let packed =
                Packed::from_raw_parts(log2, palette.into_boxed_slice(), words.into_boxed_slice());
            (Blocks::Packed(Box::new(packed)), false)
        }
        tag => {
            return Err(ProtocolError::Malformed(format!(
                "Invalid blocks tag: {tag}"
            )));
        }
    };

    // Occupancy
    let occupancy = if is_uniform {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let is_solid = cursor[0] != 0;
        *cursor = &cursor[1..];
        if is_solid {
            Occupancy::solid()
        } else {
            Occupancy::empty()
        }
    } else {
        if cursor.len() < 12288 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let mut col_y = vec![0u32; 1024];
        for item in &mut col_y {
            *item = u32::from_le_bytes(cursor[..4].try_into().unwrap());
            *cursor = &cursor[4..];
        }
        let mut col_x = vec![0u32; 1024];
        for item in &mut col_x {
            *item = u32::from_le_bytes(cursor[..4].try_into().unwrap());
            *cursor = &cursor[4..];
        }
        let mut col_z = vec![0u32; 1024];
        for item in &mut col_z {
            *item = u32::from_le_bytes(cursor[..4].try_into().unwrap());
            *cursor = &cursor[4..];
        }
        Occupancy {
            col_y: col_y.into_boxed_slice().try_into().unwrap(),
            col_x: col_x.into_boxed_slice().try_into().unwrap(),
            col_z: col_z.into_boxed_slice().try_into().unwrap(),
        }
    };

    // Light
    if cursor.is_empty() {
        return Err(ProtocolError::UnexpectedEof);
    }
    let light_tag = cursor[0];
    *cursor = &cursor[1..];

    let light = match light_tag {
        0 => None,
        1 => {
            if cursor.is_empty() {
                return Err(ProtocolError::UnexpectedEof);
            }
            let sky_tag = cursor[0];
            *cursor = &cursor[1..];
            let sky = match sky_tag {
                0 => {
                    if cursor.is_empty() {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let val = cursor[0];
                    *cursor = &cursor[1..];
                    LightLayer::Uniform(val)
                }
                1 => {
                    if cursor.len() < LIGHT_LAYER_BYTES {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let mut bytes = Box::new([0u8; LIGHT_LAYER_BYTES]);
                    bytes.copy_from_slice(&cursor[..LIGHT_LAYER_BYTES]);
                    *cursor = &cursor[LIGHT_LAYER_BYTES..];
                    LightLayer::Nibbles(bytes)
                }
                tag => {
                    return Err(ProtocolError::Malformed(format!(
                        "Invalid sky light tag: {tag}"
                    )));
                }
            };

            if cursor.is_empty() {
                return Err(ProtocolError::UnexpectedEof);
            }
            let block_tag = cursor[0];
            *cursor = &cursor[1..];
            let block = match block_tag {
                0 => {
                    if cursor.is_empty() {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let val = cursor[0];
                    *cursor = &cursor[1..];
                    LightLayer::Uniform(val)
                }
                1 => {
                    if cursor.len() < LIGHT_LAYER_BYTES {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let mut bytes = Box::new([0u8; LIGHT_LAYER_BYTES]);
                    bytes.copy_from_slice(&cursor[..LIGHT_LAYER_BYTES]);
                    *cursor = &cursor[LIGHT_LAYER_BYTES..];
                    LightLayer::Nibbles(bytes)
                }
                tag => {
                    return Err(ProtocolError::Malformed(format!(
                        "Invalid block light tag: {tag}"
                    )));
                }
            };

            Some(ChunkLight { sky, block })
        }
        tag => {
            return Err(ProtocolError::Malformed(format!(
                "Invalid light tag: {tag}"
            )));
        }
    };

    Ok(ChunkSnapshot::from_parts(
        pos, blocks, occupancy, light, 0, [0; 6], 0,
    ))
}

/// Chunk data payload carrier supporting zero-copy in-memory snapshots and bounded wire bytes.
#[derive(Debug, Clone)]
pub enum ChunkPayload {
    /// Zero-copy snapshot reference for in-process singleplayer transport.
    Snapshot(Arc<ChunkSnapshot>),
    /// Serialized byte buffer for network transport.
    Wire(BoundedVec<u8, 262_144>),
}

impl ChunkPayload {
    /// Resolves or decodes this payload into an `Arc<ChunkSnapshot>`.
    pub fn to_snapshot(&self, pos: ChunkPos) -> Result<Arc<ChunkSnapshot>> {
        match self {
            Self::Snapshot(snap) => Ok(snap.clone()),
            Self::Wire(wire) => {
                let mut cursor = wire.as_slice();
                let snap = decode_chunk_snapshot(pos, &mut cursor)?;
                Ok(Arc::new(snap))
            }
        }
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Snapshot(snap) => {
                let mut wire_bytes = Vec::new();
                encode_chunk_snapshot(snap, &mut wire_bytes);
                let bounded = BoundedVec::<u8, 262_144>::new(wire_bytes)
                    .expect("Chunk snapshot serialization exceeded 262 KiB limit");
                bounded.encode(buf);
            }
            Self::Wire(wire) => {
                wire.encode(buf);
            }
        }
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let wire = BoundedVec::<u8, 262_144>::decode(cursor)?;
        Ok(Self::Wire(wire))
    }
}

impl PartialEq for ChunkPayload {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Snapshot(a), Self::Snapshot(b)) => {
                Arc::ptr_eq(a, b)
                    || (a.position() == b.position()
                        && a.blocks() == b.blocks()
                        && a.light() == b.light())
            }
            (Self::Wire(a), Self::Wire(b)) => a == b,
            _ => false,
        }
    }
}

impl Eq for ChunkPayload {}

/// Server sends chunk voxel and light data to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cChunkData {
    /// Chunk coordinate X.
    pub chunk_x: i32,
    /// Chunk coordinate Y.
    pub chunk_y: i32,
    /// Chunk coordinate Z.
    pub chunk_z: i32,
    /// Chunk content mutation version.
    pub version: u32,
    /// Server world epoch tick counter.
    pub epoch: u32,
    /// Chunk payload (snapshot or wire bytes).
    pub payload: ChunkPayload,
}

impl S2cChunkData {
    /// Grid position of this chunk.
    #[must_use]
    pub const fn pos(&self) -> ChunkPos {
        ChunkPos::new(self.chunk_x, self.chunk_y, self.chunk_z)
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.chunk_x), buf);
        encode_varint(zigzag_i32(self.chunk_y), buf);
        encode_varint(zigzag_i32(self.chunk_z), buf);
        encode_varint(self.version, buf);
        encode_varint(self.epoch, buf);
        self.payload.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let chunk_x = unzigzag_i32(decode_varint(cursor)?);
        let chunk_y = unzigzag_i32(decode_varint(cursor)?);
        let chunk_z = unzigzag_i32(decode_varint(cursor)?);
        let version = decode_varint(cursor)?;
        let epoch = decode_varint(cursor)?;
        let payload = ChunkPayload::decode(cursor)?;

        if chunk_x.abs() > 1_000_000
            || chunk_z.abs() > 1_000_000
            || !(-100..=200).contains(&chunk_y)
        {
            return Err(ProtocolError::InvalidValue {
                field: "chunk_pos",
                reason: "Chunk coordinates out of allowable world bounds".to_string(),
            });
        }

        Ok(Self {
            chunk_x,
            chunk_y,
            chunk_z,
            version,
            epoch,
            payload,
        })
    }
}

/// Server sends lightweight uniform chunk descriptor (0-byte payload elision).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cUniformChunk {
    /// Chunk coordinate X.
    pub chunk_x: i32,
    /// Chunk coordinate Y.
    pub chunk_y: i32,
    /// Chunk coordinate Z.
    pub chunk_z: i32,
    /// Chunk content mutation version.
    pub version: u32,
    /// Uniform block state throughout chunk.
    pub block_state: BlockStateId,
    /// Uniform sky light level (0..=15).
    pub sky_light: u8,
    /// Uniform block light level (0..=15).
    pub block_light: u8,
}

impl S2cUniformChunk {
    /// Grid position of this chunk.
    #[must_use]
    pub const fn pos(&self) -> ChunkPos {
        ChunkPos::new(self.chunk_x, self.chunk_y, self.chunk_z)
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.chunk_x), buf);
        encode_varint(zigzag_i32(self.chunk_y), buf);
        encode_varint(zigzag_i32(self.chunk_z), buf);
        encode_varint(self.version, buf);
        encode_varint(self.block_state.0, buf);
        buf.push(self.sky_light);
        buf.push(self.block_light);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let chunk_x = unzigzag_i32(decode_varint(cursor)?);
        let chunk_y = unzigzag_i32(decode_varint(cursor)?);
        let chunk_z = unzigzag_i32(decode_varint(cursor)?);
        let version = decode_varint(cursor)?;
        let block_state = BlockStateId(decode_varint(cursor)?);
        if cursor.len() < 2 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let sky_light = cursor[0];
        let block_light = cursor[1];
        *cursor = &cursor[2..];

        if chunk_x.abs() > 1_000_000
            || chunk_z.abs() > 1_000_000
            || !(-100..=200).contains(&chunk_y)
        {
            return Err(ProtocolError::InvalidValue {
                field: "chunk_pos",
                reason: "Chunk coordinates out of allowable world bounds".to_string(),
            });
        }
        if sky_light > 15 || block_light > 15 {
            return Err(ProtocolError::InvalidValue {
                field: "light",
                reason: format!(
                    "Light level out of range 0..=15: sky={sky_light}, block={block_light}"
                ),
            });
        }

        Ok(Self {
            chunk_x,
            chunk_y,
            chunk_z,
            version,
            block_state,
            sky_light,
            block_light,
        })
    }

    /// Converts this uniform chunk into a `ChunkSnapshot`.
    #[must_use]
    pub fn to_snapshot(&self, is_opaque: bool) -> ChunkSnapshot {
        let light = ChunkLight {
            sky: LightLayer::uniform(self.sky_light),
            block: LightLayer::uniform(self.block_light),
        };
        ChunkSnapshot::new_uniform(self.pos(), self.block_state, is_opaque, Some(light))
    }
}

/// Server notifies client to evict chunk outside view distance.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cChunkUnload {
    /// Chunk coordinate X.
    pub chunk_x: i32,
    /// Chunk coordinate Y.
    pub chunk_y: i32,
    /// Chunk coordinate Z.
    pub chunk_z: i32,
}

impl S2cChunkUnload {
    /// Grid position of this chunk.
    #[must_use]
    pub const fn pos(&self) -> ChunkPos {
        ChunkPos::new(self.chunk_x, self.chunk_y, self.chunk_z)
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.chunk_x), buf);
        encode_varint(zigzag_i32(self.chunk_y), buf);
        encode_varint(zigzag_i32(self.chunk_z), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let chunk_x = unzigzag_i32(decode_varint(cursor)?);
        let chunk_y = unzigzag_i32(decode_varint(cursor)?);
        let chunk_z = unzigzag_i32(decode_varint(cursor)?);

        if chunk_x.abs() > 1_000_000
            || chunk_z.abs() > 1_000_000
            || !(-100..=200).contains(&chunk_y)
        {
            return Err(ProtocolError::InvalidValue {
                field: "chunk_pos",
                reason: "Chunk coordinates out of allowable world bounds".to_string(),
            });
        }

        Ok(Self {
            chunk_x,
            chunk_y,
            chunk_z,
        })
    }
}

/// LOD node payload carrier supporting zero-copy in-memory buffers and bounded wire bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LodPayload {
    /// Zero-copy buffer reference for in-process singleplayer transport.
    Memory(Arc<Vec<u32>>),
    /// Serialized byte buffer for network transport.
    Wire(BoundedVec<u8, 262_144>),
}

impl LodPayload {
    /// Extracts the underlying `u32` words from the payload.
    #[must_use]
    pub fn to_words(&self) -> Vec<u32> {
        match self {
            Self::Memory(vec) => (**vec).clone(),
            Self::Wire(wire) => {
                let bytes = wire.as_slice();
                let (chunks, _) = bytes.as_chunks::<4>();
                let mut words = Vec::with_capacity(chunks.len());
                for chunk in chunks {
                    words.push(u32::from_le_bytes(*chunk));
                }
                words
            }
        }
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Memory(vec) => {
                let byte_len = vec.len() * 4;
                let mut wire_bytes = Vec::with_capacity(byte_len);
                for w in vec.iter() {
                    wire_bytes.extend_from_slice(&w.to_le_bytes());
                }
                let bounded = BoundedVec::<u8, 262_144>::new(wire_bytes)
                    .expect("LOD mesh serialization exceeded 262 KiB limit");
                bounded.encode(buf);
            }
            Self::Wire(wire) => {
                wire.encode(buf);
            }
        }
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let wire = BoundedVec::<u8, 262_144>::decode(cursor)?;
        Ok(Self::Wire(wire))
    }
}

/// Server sends greedy-meshed LOD node geometry and palette to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cLodNodeData {
    /// Clipmap hierarchy level (L >= 1).
    pub level: u8,
    /// Node coordinate X in level-L grid.
    pub node_x: i32,
    /// Node coordinate Y in level-L grid.
    pub node_y: i32,
    /// Node coordinate Z in level-L grid.
    pub node_z: i32,
    /// Content version for eviction/replacement tracking.
    pub version: u64,
    /// Number of 8-byte quads packed in payload.
    pub quad_count: u32,
    /// Number of RGBA8 palette entries trailing quads in payload.
    pub palette_count: u32,
    /// LOD payload (quads + palette as u32 words).
    pub payload: LodPayload,
}

impl S2cLodNodeData {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.push(self.level);
        encode_varint(zigzag_i32(self.node_x), buf);
        encode_varint(zigzag_i32(self.node_y), buf);
        encode_varint(zigzag_i32(self.node_z), buf);
        encode_varlong(self.version, buf);
        encode_varint(self.quad_count, buf);
        encode_varint(self.palette_count, buf);
        self.payload.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let level = cursor[0];
        *cursor = &cursor[1..];
        let node_x = unzigzag_i32(decode_varint(cursor)?);
        let node_y = unzigzag_i32(decode_varint(cursor)?);
        let node_z = unzigzag_i32(decode_varint(cursor)?);
        let version = decode_varlong(cursor)?;
        let quad_count = decode_varint(cursor)?;
        let palette_count = decode_varint(cursor)?;
        let payload = LodPayload::decode(cursor)?;

        if !(1..=16).contains(&level) {
            return Err(ProtocolError::InvalidValue {
                field: "level",
                reason: format!("LOD level {level} out of range 1..=16"),
            });
        }
        if node_x.abs() > 1_000_000 || node_z.abs() > 1_000_000 || !(-100..=200).contains(&node_y) {
            return Err(ProtocolError::InvalidValue {
                field: "node_pos",
                reason: "LOD node coordinates out of bounds".to_string(),
            });
        }

        Ok(Self {
            level,
            node_x,
            node_y,
            node_z,
            version,
            quad_count,
            palette_count,
            payload,
        })
    }
}

/// Server instructs client to evict LOD node outside view distance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct S2cLodNodeUnload {
    /// Clipmap hierarchy level (L >= 1).
    pub level: u8,
    /// Node coordinate X in level-L grid.
    pub node_x: i32,
    /// Node coordinate Y in level-L grid.
    pub node_y: i32,
    /// Node coordinate Z in level-L grid.
    pub node_z: i32,
}

impl S2cLodNodeUnload {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.push(self.level);
        encode_varint(zigzag_i32(self.node_x), buf);
        encode_varint(zigzag_i32(self.node_y), buf);
        encode_varint(zigzag_i32(self.node_z), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let level = cursor[0];
        *cursor = &cursor[1..];
        let node_x = unzigzag_i32(decode_varint(cursor)?);
        let node_y = unzigzag_i32(decode_varint(cursor)?);
        let node_z = unzigzag_i32(decode_varint(cursor)?);

        if !(1..=16).contains(&level) {
            return Err(ProtocolError::InvalidValue {
                field: "level",
                reason: format!("LOD level {level} out of range 1..=16"),
            });
        }
        if node_x.abs() > 1_000_000 || node_z.abs() > 1_000_000 || !(-100..=200).contains(&node_y) {
            return Err(ProtocolError::InvalidValue {
                field: "node_pos",
                reason: "LOD node coordinates out of bounds".to_string(),
            });
        }

        Ok(Self {
            level,
            node_x,
            node_y,
            node_z,
        })
    }
}

/// Kind of block action initiated by client.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockActionKind {
    /// Destroy the targeted block.
    Break,
    /// Place a block against the targeted face.
    Place {
        /// Target block state to place.
        state_id: BlockStateId,
        /// Face index against which the block was placed.
        hit_face: u8,
    },
    /// Interact with or toggle the targeted block (e.g. switch / lever).
    Interact,
}

impl BlockActionKind {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Break => buf.push(0),
            Self::Place { state_id, hit_face } => {
                buf.push(1);
                encode_varint(state_id.as_u32(), buf);
                buf.push(*hit_face);
            }
            Self::Interact => buf.push(2),
        }
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let kind = cursor[0];
        *cursor = &cursor[1..];
        match kind {
            0 => Ok(Self::Break),
            1 => {
                let state_id = BlockStateId::new(decode_varint(cursor)?);
                if cursor.is_empty() {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let hit_face = cursor[0];
                if hit_face > 5 {
                    return Err(ProtocolError::InvalidValue {
                        field: "hit_face",
                        reason: format!("Hit face {hit_face} out of valid range 0..=5"),
                    });
                }
                *cursor = &cursor[1..];
                Ok(Self::Place { state_id, hit_face })
            }
            2 => Ok(Self::Interact),
            other => Err(ProtocolError::Malformed(format!(
                "Unknown block action kind {other}"
            ))),
        }
    }
}

/// Client sends block break or place action to server.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sBlockAction {
    /// Monotonically increasing sequence number for prediction reconciliation.
    pub sequence: u32,
    /// Action kind: break or place.
    pub action: BlockActionKind,
    /// World block X coordinate.
    pub x: i32,
    /// World block Y coordinate.
    pub y: i32,
    /// World block Z coordinate.
    pub z: i32,
    /// Client simulation tick at the moment the action was triggered.
    pub input_tick: u32,
}

impl C2sBlockAction {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.sequence, buf);
        self.action.encode(buf);
        encode_varint(zigzag_i32(self.x), buf);
        encode_varint(zigzag_i32(self.y), buf);
        encode_varint(zigzag_i32(self.z), buf);
        encode_varint(self.input_tick, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sequence = decode_varint(cursor)?;
        let action = BlockActionKind::decode(cursor)?;
        let x = unzigzag_i32(decode_varint(cursor)?);
        let y = unzigzag_i32(decode_varint(cursor)?);
        let z = unzigzag_i32(decode_varint(cursor)?);
        let input_tick = decode_varint(cursor)?;

        if x.abs() > 30_000_000 || z.abs() > 30_000_000 || !(-2000..=5000).contains(&y) {
            return Err(ProtocolError::InvalidValue {
                field: "block_pos",
                reason: "Block coordinates out of world bounds".to_string(),
            });
        }

        Ok(Self {
            sequence,
            action,
            x,
            y,
            z,
            input_tick,
        })
    }
}

/// Server notifies client of an updated block state in the world.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cBlockUpdate {
    /// World block X coordinate.
    pub x: i32,
    /// World block Y coordinate.
    pub y: i32,
    /// World block Z coordinate.
    pub z: i32,
    /// Updated block state ID.
    pub state_id: BlockStateId,
    /// Chunk content version.
    pub version: u64,
}

impl S2cBlockUpdate {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.x), buf);
        encode_varint(zigzag_i32(self.y), buf);
        encode_varint(zigzag_i32(self.z), buf);
        encode_varint(self.state_id.as_u32(), buf);
        encode_varlong(self.version, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let x = unzigzag_i32(decode_varint(cursor)?);
        let y = unzigzag_i32(decode_varint(cursor)?);
        let z = unzigzag_i32(decode_varint(cursor)?);
        let state_id = BlockStateId::new(decode_varint(cursor)?);
        let version = decode_varlong(cursor)?;

        if x.abs() > 30_000_000 || z.abs() > 30_000_000 || !(-2000..=5000).contains(&y) {
            return Err(ProtocolError::InvalidValue {
                field: "block_pos",
                reason: "Block coordinates out of world bounds".to_string(),
            });
        }

        Ok(Self {
            x,
            y,
            z,
            state_id,
            version,
        })
    }
}

/// Server acknowledges client predicted block actions up to a given sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cBlockActionAck {
    /// Highest acknowledged action sequence number.
    pub sequence: u32,
}

impl S2cBlockActionAck {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.sequence, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sequence = decode_varint(cursor)?;
        Ok(Self { sequence })
    }
}

/// Server synchronizes world age and time of day to clients.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cUpdateTime {
    /// Total ticks elapsed in the world since generation.
    pub world_age: u64,
    /// Current time of day in ticks (0..24000).
    pub time_of_day: u64,
}

impl S2cUpdateTime {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.world_age, buf);
        encode_varlong(self.time_of_day, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let world_age = decode_varlong(cursor)?;
        let time_of_day = decode_varlong(cursor)?;
        Ok(Self {
            world_age,
            time_of_day,
        })
    }
}

/// Server synchronizes player health, hunger, saturation, and experience stats.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cUpdateStats {
    /// Current player health in half-hearts (0.0..=20.0).
    pub health: f32,
    /// Maximum player health (typically 20.0).
    pub max_health: f32,
    /// Current hunger level in half-drumsticks (0..=20).
    pub food: u32,
    /// Hidden saturation buffer protecting food level (0.0..=food).
    pub saturation: f32,
    /// Current experience level.
    pub xp_level: u32,
    /// Current level bar progress fraction (0.0..=1.0).
    pub xp_progress: f32,
}

impl S2cUpdateStats {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&self.health.to_le_bytes());
        buf.extend_from_slice(&self.max_health.to_le_bytes());
        encode_varint(self.food, buf);
        buf.extend_from_slice(&self.saturation.to_le_bytes());
        encode_varint(self.xp_level, buf);
        buf.extend_from_slice(&self.xp_progress.to_le_bytes());
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.len() < 8 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let health = f32::from_le_bytes(cursor[..4].try_into().unwrap());
        let max_health = f32::from_le_bytes(cursor[4..8].try_into().unwrap());
        *cursor = &cursor[8..];

        let food = decode_varint(cursor)?;

        if cursor.len() < 4 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let saturation = f32::from_le_bytes(cursor[..4].try_into().unwrap());
        *cursor = &cursor[4..];

        let xp_level = decode_varint(cursor)?;

        if cursor.len() < 4 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let xp_progress = f32::from_le_bytes(cursor[..4].try_into().unwrap());
        *cursor = &cursor[4..];

        if !health.is_finite()
            || !max_health.is_finite()
            || !saturation.is_finite()
            || !xp_progress.is_finite()
            || food > 100
            || !(0.0..=1.0).contains(&xp_progress)
        {
            return Err(ProtocolError::InvalidValue {
                field: "update_stats",
                reason: "Survival stats contains NaN, negative, or out-of-range value".to_string(),
            });
        }

        Ok(Self {
            health,
            max_health,
            food,
            saturation,
            xp_level,
            xp_progress,
        })
    }
}

/// A compact item stack description in network packets.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SlotData {
    /// Item identifier (0 = Air / Empty).
    pub item: u32,
    /// Number of items (0 = Empty, max 64).
    pub count: u16,
}

impl SlotData {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.item, buf);
        encode_varint(u32::from(self.count), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let item = decode_varint(cursor)?;
        let count_raw = decode_varint(cursor)?;
        if count_raw > 64 {
            return Err(ProtocolError::InvalidValue {
                field: "slot_data.count",
                reason: "Stack count exceeds 64".to_string(),
            });
        }
        let count = count_raw as u16;
        let item = if count == 0 { 0 } else { item };
        Ok(Self { item, count })
    }
}

/// Server updates a single inventory slot on the client.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cInventorySlot {
    /// Slot index (0..35).
    pub slot: u16,
    /// Item identifier.
    pub item: u32,
    /// Stack count.
    pub count: u16,
}

impl S2cInventorySlot {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(u32::from(self.slot), buf);
        encode_varint(self.item, buf);
        encode_varint(u32::from(self.count), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let slot = decode_varint(cursor)? as u16;
        let item = decode_varint(cursor)?;
        let count_raw = decode_varint(cursor)?;
        if slot >= 64 {
            return Err(ProtocolError::InvalidValue {
                field: "inventory_slot.slot",
                reason: "Slot index out of bounds".to_string(),
            });
        }
        if count_raw > 64 {
            return Err(ProtocolError::InvalidValue {
                field: "inventory_slot.count",
                reason: "Stack count exceeds 64".to_string(),
            });
        }
        let count = count_raw as u16;
        let item = if count == 0 { 0 } else { item };
        Ok(Self { slot, item, count })
    }
}

/// Server synchronizes the entire player inventory (up to 64 slots + carried).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cInventoryBulk {
    /// All inventory slots.
    pub slots: BoundedVec<SlotData, 64>,
    /// Carried cursor slot.
    pub carried: SlotData,
}

impl S2cInventoryBulk {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.slots.encode_with(buf, SlotData::encode);
        self.carried.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let slots = BoundedVec::<SlotData, 64>::decode_with(cursor, SlotData::decode)?;
        let carried = SlotData::decode(cursor)?;
        Ok(Self { slots, carried })
    }
}

/// Client clicks on an inventory slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sInventoryClick {
    /// Slot index clicked (0..63).
    pub slot: u16,
    /// Mouse button: 0 = Left, 1 = Right.
    pub button: u8,
    /// Interaction mode: 0 = Pickup, 1 = `QuickMove`, 2 = `SwapHotbar`, 3 = Drop.
    pub mode: u8,
    /// Predicted carried item identifier before the click.
    pub predicted_carried_item: u32,
    /// Predicted carried item count before the click.
    pub predicted_carried_count: u16,
}

impl C2sInventoryClick {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(u32::from(self.slot), buf);
        buf.push(self.button);
        buf.push(self.mode);
        encode_varint(self.predicted_carried_item, buf);
        encode_varint(u32::from(self.predicted_carried_count), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let slot = decode_varint(cursor)? as u16;
        if cursor.len() < 2 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let button = cursor[0];
        let mode = cursor[1];
        *cursor = &cursor[2..];

        let predicted_carried_item = decode_varint(cursor)?;
        let predicted_carried_count = decode_varint(cursor)? as u16;

        if slot >= 64 || button > 1 || mode > 3 || predicted_carried_count > 64 {
            return Err(ProtocolError::InvalidValue {
                field: "inventory_click",
                reason: "Invalid slot, button, mode, or count".to_string(),
            });
        }

        Ok(Self {
            slot,
            button,
            mode,
            predicted_carried_item,
            predicted_carried_count,
        })
    }
}

/// Kinds of debug and gameplay player commands sent by the client.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PlayerCommandKind {
    /// Deal test damage to player.
    Damage(f32),
    /// Heal player health.
    Heal(f32),
    /// Set food level (0..20).
    SetFood(u32),
    /// Grant experience points.
    AddXp(u32),
    /// Set weather condition (0 = Clear, 1 = Rain, 2 = Thunder).
    SetWeather(u8),
    /// Trigger immediate lightning flash.
    TriggerLightning,
    /// Spawn a mob of type at world coordinates (for debugging / admin).
    SpawnMob {
        /// Entity type (1 = Zombie, 2 = Pig, 3 = Cow).
        mob_type: u8,
        /// World X coordinate.
        x: f64,
        /// World Y coordinate.
        y: f64,
        /// World Z coordinate.
        z: f64,
    },
    /// Clear all active mobs.
    ClearMobs,
    /// Switch player game mode (0 = Survival, 1 = Creative).
    SetGameMode(u8),
}

/// Server synchronizes weather condition, rain/thunder levels, and lightning flash to clients.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cUpdateWeather {
    /// Rain intensity factor in [0.0, 1.0].
    pub rain_level: f32,
    /// Thunderstorm intensity factor in [0.0, 1.0].
    pub thunder_level: f32,
    /// Remaining ticks of active lightning flash illumination (0 if dark).
    pub lightning_flash: u8,
}

impl S2cUpdateWeather {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&self.rain_level.to_le_bytes());
        buf.extend_from_slice(&self.thunder_level.to_le_bytes());
        buf.push(self.lightning_flash);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.len() < 9 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let rain_level = f32::from_le_bytes(cursor[..4].try_into().unwrap());
        let thunder_level = f32::from_le_bytes(cursor[4..8].try_into().unwrap());
        let lightning_flash = cursor[8];
        *cursor = &cursor[9..];

        if !rain_level.is_finite() || !(0.0..=1.0).contains(&rain_level) {
            return Err(ProtocolError::InvalidValue {
                field: "update_weather.rain_level",
                reason: "Rain level must be finite in [0.0, 1.0]".to_string(),
            });
        }
        if !thunder_level.is_finite() || !(0.0..=1.0).contains(&thunder_level) {
            return Err(ProtocolError::InvalidValue {
                field: "update_weather.thunder_level",
                reason: "Thunder level must be finite in [0.0, 1.0]".to_string(),
            });
        }

        Ok(Self {
            rain_level,
            thunder_level,
            lightning_flash,
        })
    }
}

/// Server spawns a new living entity in the client's simulation area.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cSpawnEntity {
    /// Network ID of the spawned entity.
    pub net_id: u32,
    /// Entity type category (1 = Zombie, 2 = Pig, 3 = Cow).
    pub entity_type: u8,
    /// World position X.
    pub x: f64,
    /// World position Y.
    pub y: f64,
    /// World position Z.
    pub z: f64,
    /// Body yaw in degrees.
    pub yaw: f32,
    /// Pitch angle in degrees.
    pub pitch: f32,
    /// Head yaw in degrees.
    pub head_yaw: f32,
    /// Current health points.
    pub health: f32,
    /// Maximum health points.
    pub max_health: f32,
}

impl S2cSpawnEntity {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.net_id, buf);
        buf.push(self.entity_type);
        buf.extend_from_slice(&self.x.to_le_bytes());
        buf.extend_from_slice(&self.y.to_le_bytes());
        buf.extend_from_slice(&self.z.to_le_bytes());
        buf.extend_from_slice(&self.yaw.to_le_bytes());
        buf.extend_from_slice(&self.pitch.to_le_bytes());
        buf.extend_from_slice(&self.head_yaw.to_le_bytes());
        buf.extend_from_slice(&self.health.to_le_bytes());
        buf.extend_from_slice(&self.max_health.to_le_bytes());
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let net_id = decode_varint(cursor)?;
        if cursor.len() < 45 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let entity_type = cursor[0];
        let x = f64::from_le_bytes(cursor[1..9].try_into().unwrap());
        let y = f64::from_le_bytes(cursor[9..17].try_into().unwrap());
        let z = f64::from_le_bytes(cursor[17..25].try_into().unwrap());
        let yaw = f32::from_le_bytes(cursor[25..29].try_into().unwrap());
        let pitch = f32::from_le_bytes(cursor[29..33].try_into().unwrap());
        let head_yaw = f32::from_le_bytes(cursor[33..37].try_into().unwrap());
        let health = f32::from_le_bytes(cursor[37..41].try_into().unwrap());
        let max_health = f32::from_le_bytes(cursor[41..45].try_into().unwrap());
        *cursor = &cursor[45..];

        if entity_type > 10 {
            return Err(ProtocolError::InvalidValue {
                field: "spawn_entity.entity_type",
                reason: "Entity type exceeds allowable range".to_string(),
            });
        }
        if !x.is_finite() || !y.is_finite() || !z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "spawn_entity.pos",
                reason: "Entity coordinates must be finite".to_string(),
            });
        }
        if !yaw.is_finite() || !pitch.is_finite() || !head_yaw.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "spawn_entity.rot",
                reason: "Entity rotation angles must be finite".to_string(),
            });
        }
        if !health.is_finite() || !max_health.is_finite() || health < 0.0 || max_health <= 0.0 {
            return Err(ProtocolError::InvalidValue {
                field: "spawn_entity.health",
                reason: "Entity health must be positive and finite".to_string(),
            });
        }

        Ok(Self {
            net_id,
            entity_type,
            x,
            y,
            z,
            yaw,
            pitch,
            head_yaw,
            health,
            max_health,
        })
    }
}

/// Server despawns one or more entities from the client's simulation area.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cDespawnEntity {
    /// List of entity network IDs to remove (max 64 per packet).
    pub net_ids: BoundedVec<u32, 64>,
}

impl S2cDespawnEntity {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.net_ids.encode_with(buf, |id, b| encode_varint(*id, b));
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let net_ids = BoundedVec::<u32, 64>::decode_with(cursor, decode_varint)?;
        Ok(Self { net_ids })
    }
}

/// Server replicates movement and rotation update for an active entity.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cEntityMove {
    /// Network ID of the moving entity.
    pub net_id: u32,
    /// World position X.
    pub x: f64,
    /// World position Y.
    pub y: f64,
    /// World position Z.
    pub z: f64,
    /// Body yaw in degrees.
    pub yaw: f32,
    /// Pitch angle in degrees.
    pub pitch: f32,
    /// Head yaw in degrees.
    pub head_yaw: f32,
    /// Ground contact flag.
    pub on_ground: bool,
}

impl S2cEntityMove {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.net_id, buf);
        buf.extend_from_slice(&self.x.to_le_bytes());
        buf.extend_from_slice(&self.y.to_le_bytes());
        buf.extend_from_slice(&self.z.to_le_bytes());
        buf.extend_from_slice(&self.yaw.to_le_bytes());
        buf.extend_from_slice(&self.pitch.to_le_bytes());
        buf.extend_from_slice(&self.head_yaw.to_le_bytes());
        buf.push(u8::from(self.on_ground));
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let net_id = decode_varint(cursor)?;
        if cursor.len() < 37 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let x = f64::from_le_bytes(cursor[..8].try_into().unwrap());
        let y = f64::from_le_bytes(cursor[8..16].try_into().unwrap());
        let z = f64::from_le_bytes(cursor[16..24].try_into().unwrap());
        let yaw = f32::from_le_bytes(cursor[24..28].try_into().unwrap());
        let pitch = f32::from_le_bytes(cursor[28..32].try_into().unwrap());
        let head_yaw = f32::from_le_bytes(cursor[32..36].try_into().unwrap());
        let on_ground = cursor[36] != 0;
        *cursor = &cursor[37..];

        if !x.is_finite() || !y.is_finite() || !z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "entity_move.pos",
                reason: "Coordinates must be finite".to_string(),
            });
        }
        if !yaw.is_finite() || !pitch.is_finite() || !head_yaw.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "entity_move.rot",
                reason: "Rotations must be finite".to_string(),
            });
        }

        Ok(Self {
            net_id,
            x,
            y,
            z,
            yaw,
            pitch,
            head_yaw,
            on_ground,
        })
    }
}

/// Server broadcasts entity event or animation status (hurt, death).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cEntityStatus {
    /// Network ID of the affected entity.
    pub net_id: u32,
    /// Event status code (2 = hurt red flash, 3 = death).
    pub status: u8,
}

impl S2cEntityStatus {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.net_id, buf);
        buf.push(self.status);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let net_id = decode_varint(cursor)?;
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let status = cursor[0];
        *cursor = &cursor[1..];
        Ok(Self { net_id, status })
    }
}

/// Client attacks or interacts with an entity in range.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sInteractEntity {
    /// Network ID of the target entity.
    pub target_net_id: u32,
    /// Action type (0 = Attack, 1 = Interact).
    pub action: u8,
}

impl C2sInteractEntity {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.target_net_id, buf);
        buf.push(self.action);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let target_net_id = decode_varint(cursor)?;
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let action = cursor[0];
        *cursor = &cursor[1..];
        if action > 1 {
            return Err(ProtocolError::InvalidValue {
                field: "interact_entity.action",
                reason: "Action must be 0 (Attack) or 1 (Interact)".to_string(),
            });
        }
        Ok(Self {
            target_net_id,
            action,
        })
    }
}

/// Client sends an interactive player command or debug action to server.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct C2sPlayerCommand {
    /// Command payload.
    pub command: PlayerCommandKind,
}

impl C2sPlayerCommand {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self.command {
            PlayerCommandKind::Damage(amt) => {
                buf.push(0);
                buf.extend_from_slice(&amt.to_le_bytes());
            }
            PlayerCommandKind::Heal(amt) => {
                buf.push(1);
                buf.extend_from_slice(&amt.to_le_bytes());
            }
            PlayerCommandKind::SetFood(food) => {
                buf.push(2);
                encode_varint(food, buf);
            }
            PlayerCommandKind::AddXp(pts) => {
                buf.push(3);
                encode_varint(pts, buf);
            }
            PlayerCommandKind::SetWeather(w) => {
                buf.push(4);
                buf.push(w);
            }
            PlayerCommandKind::TriggerLightning => {
                buf.push(5);
            }
            PlayerCommandKind::SpawnMob { mob_type, x, y, z } => {
                buf.push(6);
                buf.push(mob_type);
                buf.extend_from_slice(&x.to_le_bytes());
                buf.extend_from_slice(&y.to_le_bytes());
                buf.extend_from_slice(&z.to_le_bytes());
            }
            PlayerCommandKind::ClearMobs => {
                buf.push(7);
            }
            PlayerCommandKind::SetGameMode(mode) => {
                buf.push(8);
                buf.push(mode);
            }
        }
    }

    /// Decodes from wire buffer.
    #[allow(clippy::too_many_lines)]
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let kind = cursor[0];
        *cursor = &cursor[1..];

        let command = match kind {
            0 => {
                if cursor.len() < 4 {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let amt = f32::from_le_bytes(cursor[..4].try_into().unwrap());
                *cursor = &cursor[4..];
                if !amt.is_finite() || amt < 0.0 {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.damage",
                        reason: "Amount must be finite and positive".to_string(),
                    });
                }
                PlayerCommandKind::Damage(amt)
            }
            1 => {
                if cursor.len() < 4 {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let amt = f32::from_le_bytes(cursor[..4].try_into().unwrap());
                *cursor = &cursor[4..];
                if !amt.is_finite() || amt < 0.0 {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.heal",
                        reason: "Amount must be finite and positive".to_string(),
                    });
                }
                PlayerCommandKind::Heal(amt)
            }
            2 => {
                let food = decode_varint(cursor)?;
                if food > 20 {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.food",
                        reason: "Food must be <= 20".to_string(),
                    });
                }
                PlayerCommandKind::SetFood(food)
            }
            3 => {
                let pts = decode_varint(cursor)?;
                if pts > 1_000_000 {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.xp",
                        reason: "XP points exceeds maximum limit".to_string(),
                    });
                }
                PlayerCommandKind::AddXp(pts)
            }
            4 => {
                if cursor.is_empty() {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let w = cursor[0];
                *cursor = &cursor[1..];
                if w > 2 {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.weather",
                        reason: "Weather kind must be <= 2".to_string(),
                    });
                }
                PlayerCommandKind::SetWeather(w)
            }
            5 => PlayerCommandKind::TriggerLightning,
            6 => {
                if cursor.len() < 25 {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let mob_type = cursor[0];
                let x = f64::from_le_bytes(cursor[1..9].try_into().unwrap());
                let y = f64::from_le_bytes(cursor[9..17].try_into().unwrap());
                let z = f64::from_le_bytes(cursor[17..25].try_into().unwrap());
                *cursor = &cursor[25..];
                if mob_type == 0 || mob_type > 3 {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.spawn_mob.mob_type",
                        reason: "Mob type must be 1..=3".to_string(),
                    });
                }
                if !x.is_finite() || !y.is_finite() || !z.is_finite() {
                    return Err(ProtocolError::InvalidValue {
                        field: "player_command.spawn_mob.pos",
                        reason: "Coordinates must be finite".to_string(),
                    });
                }
                PlayerCommandKind::SpawnMob { mob_type, x, y, z }
            }
            7 => PlayerCommandKind::ClearMobs,
            8 => {
                if cursor.is_empty() {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let mode = cursor[0];
                *cursor = &cursor[1..];
                PlayerCommandKind::SetGameMode(mode)
            }
            other => {
                return Err(ProtocolError::InvalidDiscriminant {
                    enum_name: "PlayerCommandKind",
                    value: u32::from(other),
                });
            }
        };

        Ok(Self { command })
    }
}

/// Client requests command completion suggestions from the server.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C2sCommandSuggest {
    /// Opaque request transaction ID.
    pub id: u32,
    /// Current input string (up to 256 bytes).
    pub command: BoundedString<256>,
    /// Cursor position in the command string.
    pub cursor: u32,
}

impl C2sCommandSuggest {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.id, buf);
        self.command.encode(buf);
        encode_varint(self.cursor, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varint(cursor)?;
        let command = BoundedString::<256>::decode(cursor)?;
        let cursor_pos = decode_varint(cursor)?;
        Ok(Self {
            id,
            command,
            cursor: cursor_pos,
        })
    }
}

/// Server provides command auto-completion suggestions for a given input range.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cCommandSuggestions {
    /// Request transaction ID matching client's query.
    pub id: u32,
    /// Start character/byte index in command string to be replaced.
    pub start: u32,
    /// Length of range in command string to be replaced.
    pub length: u32,
    /// List of suggestion completions (up to 16 matches, each <= 64 bytes).
    pub matches: BoundedVec<BoundedString<64>, 16>,
    /// Optional tooltips or argument hints for each match.
    pub tooltips: BoundedVec<BoundedString<64>, 16>,
}

impl S2cCommandSuggestions {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.id, buf);
        encode_varint(self.start, buf);
        encode_varint(self.length, buf);
        self.matches.encode_with(buf, BoundedString::encode);
        self.tooltips.encode_with(buf, BoundedString::encode);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varint(cursor)?;
        let start = decode_varint(cursor)?;
        let length = decode_varint(cursor)?;
        let matches =
            BoundedVec::<BoundedString<64>, 16>::decode_with(cursor, BoundedString::decode)?;
        let tooltips =
            BoundedVec::<BoundedString<64>, 16>::decode_with(cursor, BoundedString::decode)?;
        Ok(Self {
            id,
            start,
            length,
            matches,
            tooltips,
        })
    }
}

/// Bitflags representing player movement button states.
pub mod input_buttons {
    /// Forward movement key (e.g. W).
    pub const FORWARD: u16 = 1 << 0;
    /// Backward movement key (e.g. S).
    pub const BACK: u16 = 1 << 1;
    /// Left movement key (e.g. A).
    pub const LEFT: u16 = 1 << 2;
    /// Right movement key (e.g. D).
    pub const RIGHT: u16 = 1 << 3;
    /// Jump key (e.g. Space).
    pub const JUMP: u16 = 1 << 4;
    /// Sneak key (e.g. Left Shift).
    pub const SNEAK: u16 = 1 << 5;
    /// Sprint key (e.g. Left Ctrl).
    pub const SPRINT: u16 = 1 << 6;
    /// Fly upward key.
    pub const FLY_UP: u16 = 1 << 7;
    /// Fly downward key.
    pub const FLY_DOWN: u16 = 1 << 8;
}

/// A single sampled player movement input frame for a specific client tick.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InputFrame {
    /// Client tick number when this input was generated.
    pub tick: u32,
    /// Bitfield of movement buttons pressed (see [`input_buttons`]).
    pub buttons: u16,
    /// Quantized camera yaw (`65536 = 360` degrees).
    pub yaw: u16,
    /// Quantized camera pitch (`32767 = 90` degrees).
    pub pitch: i16,
    /// Active hotbar slot index (0..=8).
    pub hotbar: u8,
}

impl InputFrame {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.tick, buf);
        buf.extend_from_slice(&self.buttons.to_le_bytes());
        buf.extend_from_slice(&self.yaw.to_le_bytes());
        buf.extend_from_slice(&self.pitch.to_le_bytes());
        buf.push(self.hotbar);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let tick = decode_varint(cursor)?;
        if cursor.len() < 7 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let buttons = u16::from_le_bytes(cursor[..2].try_into().unwrap());
        let yaw = u16::from_le_bytes(cursor[2..4].try_into().unwrap());
        let pitch = i16::from_le_bytes(cursor[4..6].try_into().unwrap());
        let hotbar = cursor[6];
        *cursor = &cursor[7..];

        if hotbar > 8 {
            return Err(ProtocolError::InvalidValue {
                field: "hotbar",
                reason: format!("Hotbar index {hotbar} exceeds maximum 8"),
            });
        }

        Ok(Self {
            tick,
            buttons,
            yaw,
            pitch,
            hotbar,
        })
    }
}

/// Client transmits recent unacknowledged movement input frames for authoritative simulation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C2sPlayerInput {
    /// Last server tick known/acknowledged by the client.
    pub last_server_tick_ack: u32,
    /// Recent un-acknowledged input frames (up to 16), in chronological order.
    pub frames: BoundedVec<InputFrame, 16>,
}

impl C2sPlayerInput {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.last_server_tick_ack, buf);
        self.frames.encode_with(buf, InputFrame::encode);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let last_server_tick_ack = decode_varint(cursor)?;
        let frames = BoundedVec::<InputFrame, 16>::decode_with(cursor, InputFrame::decode)?;
        Ok(Self {
            last_server_tick_ack,
            frames,
        })
    }
}

/// Server replicates authoritative player movement outcome acknowledging a client tick.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cPlayerMovementAck {
    /// Client tick this authoritative outcome corresponds to.
    pub client_tick_ack: u32,
    /// Server tick during which this state was simulated.
    pub server_tick: u32,
    /// Authoritative player position X.
    pub x: f64,
    /// Authoritative player position Y.
    pub y: f64,
    /// Authoritative player position Z.
    pub z: f64,
    /// Authoritative velocity X (blocks per tick).
    pub vx: f32,
    /// Authoritative velocity Y (blocks per tick).
    pub vy: f32,
    /// Authoritative velocity Z (blocks per tick).
    pub vz: f32,
    /// Authoritative body yaw in degrees.
    pub yaw: f32,
    /// Authoritative pitch in degrees.
    pub pitch: f32,
    /// Ground contact flag.
    pub on_ground: bool,
    /// Flying state flag.
    pub flying: bool,
    /// Non-zero if server is executing a forced teleport / correction.
    pub teleport_id: u32,
}

impl Eq for S2cPlayerMovementAck {}

impl S2cPlayerMovementAck {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.client_tick_ack, buf);
        encode_varint(self.server_tick, buf);
        buf.extend_from_slice(&self.x.to_le_bytes());
        buf.extend_from_slice(&self.y.to_le_bytes());
        buf.extend_from_slice(&self.z.to_le_bytes());
        buf.extend_from_slice(&self.vx.to_le_bytes());
        buf.extend_from_slice(&self.vy.to_le_bytes());
        buf.extend_from_slice(&self.vz.to_le_bytes());
        buf.extend_from_slice(&self.yaw.to_le_bytes());
        buf.extend_from_slice(&self.pitch.to_le_bytes());
        buf.push(u8::from(self.on_ground));
        buf.push(u8::from(self.flying));
        encode_varint(self.teleport_id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let client_tick_ack = decode_varint(cursor)?;
        let server_tick = decode_varint(cursor)?;
        if cursor.len() < 46 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let x = f64::from_le_bytes(cursor[..8].try_into().unwrap());
        let y = f64::from_le_bytes(cursor[8..16].try_into().unwrap());
        let z = f64::from_le_bytes(cursor[16..24].try_into().unwrap());
        let vx = f32::from_le_bytes(cursor[24..28].try_into().unwrap());
        let vy = f32::from_le_bytes(cursor[28..32].try_into().unwrap());
        let vz = f32::from_le_bytes(cursor[32..36].try_into().unwrap());
        let yaw = f32::from_le_bytes(cursor[36..40].try_into().unwrap());
        let pitch = f32::from_le_bytes(cursor[40..44].try_into().unwrap());
        let on_ground = cursor[44] != 0;
        let flying = cursor[45] != 0;
        *cursor = &cursor[46..];
        let teleport_id = decode_varint(cursor)?;

        if !x.is_finite() || !y.is_finite() || !z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "ack.pos",
                reason: "Coordinates must be finite".to_string(),
            });
        }
        if !vx.is_finite() || !vy.is_finite() || !vz.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "ack.vel",
                reason: "Velocities must be finite".to_string(),
            });
        }

        Ok(Self {
            client_tick_ack,
            server_tick,
            x,
            y,
            z,
            vx,
            vy,
            vz,
            yaw,
            pitch,
            on_ground,
            flying,
            teleport_id,
        })
    }
}

/// Client confirms receipt and local application of server-initiated teleport.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sTeleportAck {
    /// Teleport identifier assigned by server.
    pub teleport_id: u32,
}

impl C2sTeleportAck {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.teleport_id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let teleport_id = decode_varint(cursor)?;
        Ok(Self { teleport_id })
    }
}

/// Visual particle effect categories for network replication and client-side simulation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ParticleEffectKind {
    /// Block breaking debris burst.
    BlockBreak = 0,
    /// Block placement dust puff.
    BlockPlace = 1,
    /// Material footstep dust puff.
    Footstep = 2,
    /// Smoke puff (e.g. torch or campfire).
    Smoke = 3,
    /// Flame particle (e.g. torch or fire).
    Flame = 4,
    /// Attack critical strike sparks.
    Crit = 5,
    /// Explosion shockwave and smoke.
    Explosion = 6,
    /// Entity status heart particles.
    Heart = 7,
}

impl ParticleEffectKind {
    /// Converts a wire byte code into `ParticleEffectKind`.
    #[must_use]
    pub const fn from_wire(code: u8) -> Option<Self> {
        match code {
            0 => Some(Self::BlockBreak),
            1 => Some(Self::BlockPlace),
            2 => Some(Self::Footstep),
            3 => Some(Self::Smoke),
            4 => Some(Self::Flame),
            5 => Some(Self::Crit),
            6 => Some(Self::Explosion),
            7 => Some(Self::Heart),
            _ => None,
        }
    }
}

/// Server broadcasts a visual particle emission event to clients in Play phase.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cParticleEvent {
    /// Effect kind.
    pub effect: ParticleEffectKind,
    /// World position X.
    pub x: f32,
    /// World position Y.
    pub y: f32,
    /// World position Z.
    pub z: f32,
    /// Number of particles to spawn (bounded to max 256).
    pub count: u16,
    /// Velocity / spread multiplier factor.
    pub speed: f32,
    /// Associated block state ID (for debris/dust), or auxiliary parameter.
    pub block_state_id: u32,
}

impl Eq for S2cParticleEvent {}

impl S2cParticleEvent {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.push(self.effect as u8);
        buf.extend_from_slice(&self.x.to_le_bytes());
        buf.extend_from_slice(&self.y.to_le_bytes());
        buf.extend_from_slice(&self.z.to_le_bytes());
        encode_varint(u32::from(self.count), buf);
        buf.extend_from_slice(&self.speed.to_le_bytes());
        encode_varint(self.block_state_id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let effect_byte = cursor[0];
        *cursor = &cursor[1..];
        let effect = ParticleEffectKind::from_wire(effect_byte).ok_or_else(|| {
            ProtocolError::InvalidValue {
                field: "particle.effect",
                reason: format!("Unknown particle effect code: {effect_byte}"),
            }
        })?;

        if cursor.len() < 12 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let x = f32::from_le_bytes(cursor[..4].try_into().unwrap());
        let y = f32::from_le_bytes(cursor[4..8].try_into().unwrap());
        let z = f32::from_le_bytes(cursor[8..12].try_into().unwrap());
        *cursor = &cursor[12..];

        if !x.is_finite() || !y.is_finite() || !z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "particle.pos",
                reason: "Coordinates must be finite".to_string(),
            });
        }

        let count_raw = decode_varint(cursor)?;
        if count_raw > 256 {
            return Err(ProtocolError::InvalidValue {
                field: "particle.count",
                reason: format!("Particle count {count_raw} exceeds maximum 256"),
            });
        }
        #[allow(clippy::cast_possible_truncation)]
        let count = count_raw as u16;

        if cursor.len() < 4 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let speed = f32::from_le_bytes(cursor[..4].try_into().unwrap());
        *cursor = &cursor[4..];

        if !speed.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "particle.speed",
                reason: "Particle speed must be finite".to_string(),
            });
        }

        let block_state_id = decode_varint(cursor)?;

        Ok(Self {
            effect,
            x,
            y,
            z,
            count,
            speed,
            block_state_id,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_update_time_codec_round_trip() {
        let msg = S2cUpdateTime {
            world_age: 144_000,
            time_of_day: 6_000,
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf);

        let mut cursor = &buf[..];
        let decoded = S2cUpdateTime::decode(&mut cursor).expect("failed to decode S2cUpdateTime");
        assert_eq!(msg, decoded);
        assert!(cursor.is_empty());
    }

    #[test]
    fn test_update_stats_codec_round_trip() {
        let msg = S2cUpdateStats {
            health: 18.5,
            max_health: 20.0,
            food: 19,
            saturation: 4.5,
            xp_level: 5,
            xp_progress: 0.65,
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf);

        let mut cursor = &buf[..];
        let decoded = S2cUpdateStats::decode(&mut cursor).expect("failed to decode S2cUpdateStats");
        assert_eq!(msg, decoded);
        assert!(cursor.is_empty());
    }

    #[test]
    fn test_inventory_slot_codec_round_trip() {
        let msg = S2cInventorySlot {
            slot: 4,
            item: 2,
            count: 32,
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf);

        let mut cursor = &buf[..];
        let decoded =
            S2cInventorySlot::decode(&mut cursor).expect("failed to decode S2cInventorySlot");
        assert_eq!(msg, decoded);
        assert!(cursor.is_empty());
    }

    #[test]
    fn test_inventory_click_codec_round_trip() {
        let msg = C2sInventoryClick {
            slot: 0,
            button: 0,
            mode: 0,
            predicted_carried_item: 0,
            predicted_carried_count: 0,
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf);

        let mut cursor = &buf[..];
        let decoded =
            C2sInventoryClick::decode(&mut cursor).expect("failed to decode C2sInventoryClick");
        assert_eq!(msg, decoded);
        assert!(cursor.is_empty());
    }

    #[test]
    fn test_update_weather_codec_round_trip() {
        let msg = S2cUpdateWeather {
            rain_level: 0.85,
            thunder_level: 0.42,
            lightning_flash: 3,
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf);

        let mut cursor = &buf[..];
        let decoded =
            S2cUpdateWeather::decode(&mut cursor).expect("failed to decode S2cUpdateWeather");
        assert_eq!(msg, decoded);
        assert!(cursor.is_empty());
    }

    #[test]
    #[allow(clippy::too_many_lines)]
    fn test_entity_codec_round_trip() {
        let spawn = S2cSpawnEntity {
            net_id: 42,
            entity_type: 1,
            x: 12.5,
            y: 64.0,
            z: -18.25,
            yaw: 45.0,
            pitch: -15.0,
            head_yaw: 50.0,
            health: 20.0,
            max_health: 20.0,
        };
        let mut buf = Vec::new();
        spawn.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_spawn =
            S2cSpawnEntity::decode(&mut cursor).expect("failed to decode S2cSpawnEntity");
        assert_eq!(spawn, decoded_spawn);

        let despawn_ids = BoundedVec::new(vec![42, 43]).unwrap();
        let despawn = S2cDespawnEntity {
            net_ids: despawn_ids,
        };
        let mut buf = Vec::new();
        despawn.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_despawn =
            S2cDespawnEntity::decode(&mut cursor).expect("failed to decode S2cDespawnEntity");
        assert_eq!(despawn, decoded_despawn);

        let emove = S2cEntityMove {
            net_id: 42,
            x: 13.0,
            y: 64.0,
            z: -18.0,
            yaw: 50.0,
            pitch: 0.0,
            head_yaw: 55.0,
            on_ground: true,
        };
        let mut buf = Vec::new();
        emove.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_move =
            S2cEntityMove::decode(&mut cursor).expect("failed to decode S2cEntityMove");
        assert_eq!(emove, decoded_move);

        let status = S2cEntityStatus {
            net_id: 42,
            status: 2,
        };
        let mut buf = Vec::new();
        status.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_status =
            S2cEntityStatus::decode(&mut cursor).expect("failed to decode S2cEntityStatus");
        assert_eq!(status, decoded_status);

        let interact = C2sInteractEntity {
            target_net_id: 42,
            action: 0,
        };
        let mut buf = Vec::new();
        interact.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_interact =
            C2sInteractEntity::decode(&mut cursor).expect("failed to decode C2sInteractEntity");
        assert_eq!(interact, decoded_interact);

        let frame = InputFrame {
            tick: 105,
            buttons: input_buttons::FORWARD | input_buttons::SPRINT,
            yaw: 16384,
            pitch: -2000,
            hotbar: 3,
        };
        let mut buf = Vec::new();
        frame.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_frame = InputFrame::decode(&mut cursor).expect("failed to decode InputFrame");
        assert_eq!(frame, decoded_frame);

        let input_msg = C2sPlayerInput {
            last_server_tick_ack: 100,
            frames: BoundedVec::new(vec![frame]).unwrap(),
        };
        let mut buf = Vec::new();
        input_msg.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_input =
            C2sPlayerInput::decode(&mut cursor).expect("failed to decode C2sPlayerInput");
        assert_eq!(input_msg, decoded_input);

        let ack = S2cPlayerMovementAck {
            client_tick_ack: 105,
            server_tick: 500,
            x: 12.5,
            y: 64.0,
            z: -18.75,
            vx: 0.1,
            vy: -0.05,
            vz: 0.3,
            yaw: 90.0,
            pitch: -10.0,
            on_ground: false,
            flying: true,
            teleport_id: 0,
        };
        let mut buf = Vec::new();
        ack.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_ack = S2cPlayerMovementAck::decode(&mut cursor)
            .expect("failed to decode S2cPlayerMovementAck");
        assert_eq!(ack, decoded_ack);

        let tp_ack = C2sTeleportAck { teleport_id: 42 };
        let mut buf = Vec::new();
        tp_ack.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_tp =
            C2sTeleportAck::decode(&mut cursor).expect("failed to decode C2sTeleportAck");
        assert_eq!(tp_ack, decoded_tp);

        let particle_ev = S2cParticleEvent {
            effect: ParticleEffectKind::BlockBreak,
            x: 10.5,
            y: 64.0,
            z: -5.25,
            count: 32,
            speed: 1.5,
            block_state_id: 2,
        };
        let mut buf = Vec::new();
        particle_ev.encode(&mut buf);
        let mut cursor = &buf[..];
        let decoded_ev =
            S2cParticleEvent::decode(&mut cursor).expect("failed to decode S2cParticleEvent");
        assert_eq!(particle_ev, decoded_ev);
    }
}
