//! Host execution state maintained per mod instance in Wasmtime store.

use std::sync::Arc;
use vx_core::coords::BlockPos;
use vx_sim::event::EventFilter;
use vx_voxel::state::BlockStateId;
use wasmtime::{StoreLimits, StoreLimitsBuilder};

use crate::config::ModConfig;
use crate::error::ModError;
use crate::permissions::ModPermissions;

/// A queued block edit generated by a sandboxed mod.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlockEdit {
    /// Target voxel position in world coordinates.
    pub pos: BlockPos,
    /// Block state ID to write.
    pub state: BlockStateId,
}

/// Callback function to query a block state from the host world.
pub type WorldReader = Arc<dyn Fn(BlockPos) -> Option<BlockStateId> + Send + Sync>;

/// Host state stored inside a `wasmtime::Store<HostState>`.
pub struct HostState {
    /// Unique identifier of the mod.
    pub mod_id: String,
    /// Capability flags granted to this mod.
    pub permissions: ModPermissions,
    /// Resource and execution configuration.
    pub config: ModConfig,
    /// Store resource limits enforcing linear memory limits.
    pub limits: StoreLimits,
    /// Queued block modifications waiting to be applied by the server.
    pub queued_edits: Vec<BlockEdit>,
    /// Command names registered by the mod.
    pub registered_commands: Vec<String>,
    /// Log messages emitted by the mod.
    pub log_messages: Vec<(tracing::Level, String)>,
    /// Event subscription mask for this mod.
    pub event_filter: EventFilter,
    /// Host world reader callback.
    pub world_reader: Option<WorldReader>,
    /// Count of consecutive faults/traps.
    pub fault_count: u32,
    /// Whether the mod has been suspended due to excessive faults.
    pub is_suspended: bool,
}

impl HostState {
    /// Creates a new host state for a mod with the given configuration.
    #[must_use]
    pub fn new(
        mod_id: String,
        permissions: ModPermissions,
        config: ModConfig,
        world_reader: Option<WorldReader>,
    ) -> Self {
        let limits = StoreLimitsBuilder::new()
            .memory_size(config.max_memory_bytes)
            .build();

        Self {
            mod_id,
            permissions,
            config,
            limits,
            queued_edits: Vec::new(),
            registered_commands: Vec::new(),
            log_messages: Vec::new(),
            event_filter: EventFilter::empty(),
            world_reader,
            fault_count: 0,
            is_suspended: false,
        }
    }

    /// Checks if a permission is granted, returning `ModError::Denied` if not.
    pub fn check_permission(
        &self,
        perm: ModPermissions,
        name: &'static str,
    ) -> Result<(), ModError> {
        if self.permissions.contains(perm) {
            Ok(())
        } else {
            Err(ModError::Denied {
                mod_id: self.mod_id.clone(),
                permission: name,
            })
        }
    }

    /// Queues a block edit if the quota has not been exceeded.
    pub fn queue_block_edit(&mut self, pos: BlockPos, state: BlockStateId) -> Result<(), ModError> {
        self.check_permission(ModPermissions::WORLD_WRITE, "world.write")?;
        if self.queued_edits.len() >= self.config.max_queued_edits_per_tick {
            return Err(ModError::InvalidArgument {
                mod_id: self.mod_id.clone(),
                message: format!(
                    "Queued edits quota exceeded (limit: {})",
                    self.config.max_queued_edits_per_tick
                ),
            });
        }
        self.queued_edits.push(BlockEdit { pos, state });
        Ok(())
    }

    /// Reads a block state from the host world at the specified position.
    pub fn read_block(&self, pos: BlockPos) -> Result<Option<BlockStateId>, ModError> {
        self.check_permission(ModPermissions::WORLD_READ, "world.read")?;
        if let Some(reader) = &self.world_reader {
            Ok(reader(pos))
        } else {
            Ok(None)
        }
    }

    /// Records a log message from the mod.
    pub fn record_log(&mut self, level: tracing::Level, msg: String) {
        if self.log_messages.len() < self.config.max_log_messages_per_tick {
            self.log_messages.push((level, msg));
        }
    }

    /// Subscribes to events matching the specified mask.
    pub fn subscribe_events(&mut self, filter: EventFilter) -> Result<(), ModError> {
        self.check_permission(ModPermissions::EVENTS_LISTEN, "events.listen")?;
        self.event_filter = filter;
        Ok(())
    }

    /// Registers a command handler.
    pub fn register_command(&mut self, name: String) -> Result<(), ModError> {
        self.check_permission(ModPermissions::COMMANDS_REGISTER, "command.register")?;
        if !self.registered_commands.contains(&name) {
            self.registered_commands.push(name);
        }
        Ok(())
    }

    /// Drains all queued block edits.
    pub fn drain_edits(&mut self) -> Vec<BlockEdit> {
        std::mem::take(&mut self.queued_edits)
    }

    /// Drains all collected log messages.
    pub fn drain_logs(&mut self) -> Vec<(tracing::Level, String)> {
        std::mem::take(&mut self.log_messages)
    }
}
