[package]
name = "voxel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Voxel engine client executable"

[dependencies]
vx-core = { workspace = true }
vx-gpu = { workspace = true }
vx-voxel = { workspace = true }
vx-mesh = { workspace = true }
vx-assets = { workspace = true }
vx-worldgen = { workspace = true }
vx-server = { workspace = true }
vx-net = { workspace = true }
vx-protocol = { workspace = true }
vx-lod = { workspace = true }
vx-ui = { workspace = true }
vx-sim = { workspace = true }
vx-content = { workspace = true }
vx-audio = { workspace = true }
hashbrown = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
winit = { workspace = true }
raw-window-handle = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
mimalloc = { workspace = true }
anyhow = { workspace = true }
image = { workspace = true }

[lints]
workspace = true
