//! Sandboxed mod instance runtime encapsulation.

use telos_sim::event::GameEvent;
use wasmtime::{Instance, Store, TypedFunc};

use crate::error::{ModError, ModResult};
use crate::host_state::{BlockEdit, HostState};

/// Simple 32-bit FNV-1a hash function for strings.
#[must_use]
pub fn hash_str_32(s: &str) -> u32 {
    let mut hash = 0x811c_9dc5u32;
    for b in s.as_bytes() {
        hash ^= u32::from(*b);
        hash = hash.wrapping_mul(0x0100_0193);
    }
    hash
}

/// An instantiated, sandboxed WASM mod.
pub struct LoadedMod {
    mod_id: String,
    store: Store<HostState>,
    instance: Instance,
}

impl LoadedMod {
    /// Creates a new `LoadedMod` instance, wiring the store limiter.
    pub fn new(mod_id: String, mut store: Store<HostState>, instance: Instance) -> Self {
        store.limiter(|state| &mut state.limits);

        Self {
            mod_id,
            store,
            instance,
        }
    }

    /// Returns the unique identifier of the mod.
    #[must_use]
    pub fn mod_id(&self) -> &str {
        &self.mod_id
    }

    /// Returns whether the mod has been suspended due to runtime faults.
    #[must_use]
    pub fn is_suspended(&self) -> bool {
        self.store.data().is_suspended
    }

    /// Returns a reference to the inner host state.
    #[must_use]
    pub fn state(&self) -> &HostState {
        self.store.data()
    }

    /// Returns a mutable reference to the inner host state.
    pub fn state_mut(&mut self) -> &mut HostState {
        self.store.data_mut()
    }

    /// Drains any queued block modifications generated by this mod.
    pub fn drain_edits(&mut self) -> Vec<BlockEdit> {
        self.store.data_mut().drain_edits()
    }

    /// Drains any log messages emitted by this mod.
    pub fn drain_logs(&mut self) -> Vec<(tracing::Level, String)> {
        self.store.data_mut().drain_logs()
    }

    /// Refills fuel and calls the mod's initialization routine (`_start`, `telos_init`, or `init`).
    pub fn call_init(&mut self) -> ModResult<()> {
        if self.is_suspended() {
            return Ok(());
        }

        self.refill_fuel()?;

        // Look for init functions
        let init_names = ["telos_init", "_start", "init"];
        for name in init_names {
            if let Ok(func) = self
                .instance
                .get_typed_func::<(), ()>(&mut self.store, name)
            {
                return self.invoke_guest_func(&func, ());
            }
        }

        Ok(())
    }

    /// Dispatches a single game event to the mod if subscribed.
    pub fn call_on_event(&mut self, event: &GameEvent) -> ModResult<()> {
        if self.is_suspended() {
            return Ok(());
        }

        // Check subscription filter
        if !self.store.data().event_filter.matches(event) {
            return Ok(());
        }

        let (event_id, p1, p2, p3, p4) = match event {
            GameEvent::BlockBroken {
                pos,
                old_state,
                actor_net_id: _,
            } => (
                1i32,
                i64::from(pos.x()),
                i64::from(pos.y()),
                i64::from(pos.z()),
                i64::from(old_state.0),
            ),
            GameEvent::BlockPlaced {
                pos,
                new_state,
                actor_net_id: _,
            } => (
                2i32,
                i64::from(pos.x()),
                i64::from(pos.y()),
                i64::from(pos.z()),
                i64::from(new_state.0),
            ),
            GameEvent::EntityDamage {
                target_net_id,
                damage,
                attacker_net_id,
            } => (
                3i32,
                i64::from(*target_net_id),
                i64::from(damage.to_bits()),
                i64::from(attacker_net_id.unwrap_or(u32::MAX)),
                0i64,
            ),
            GameEvent::Tick { tick } => (
                4i32,
                i64::try_from(*tick).unwrap_or(i64::MAX),
                0i64,
                0i64,
                0i64,
            ),
            GameEvent::PlayerJoined { entity_net_id, .. } => {
                (5i32, i64::from(*entity_net_id), 0i64, 0i64, 0i64)
            }
            GameEvent::PlayerLeft { entity_net_id, .. } => {
                (6i32, i64::from(*entity_net_id), 0i64, 0i64, 0i64)
            }
        };

        self.refill_fuel()?;

        let func_names = ["telos_on_event", "on_event"];
        for name in func_names {
            if let Ok(func) = self
                .instance
                .get_typed_func::<(i32, i64, i64, i64, i64), i32>(&mut self.store, name)
            {
                let _ = self.invoke_guest_func(&func, (event_id, p1, p2, p3, p4))?;
                return Ok(());
            }
        }

        Ok(())
    }

    /// Dispatches a command invocation to the mod.
    pub fn call_on_command(&mut self, cmd: &str, args: &str) -> ModResult<bool> {
        if self.is_suspended() {
            return Ok(false);
        }

        if !self
            .store
            .data()
            .registered_commands
            .iter()
            .any(|c| c == cmd)
        {
            return Ok(false);
        }

        self.refill_fuel()?;

        let cmd_hash = hash_str_32(cmd);
        let arg_len = i64::try_from(args.len()).unwrap_or(i64::MAX);

        let func_names = ["telos_on_command", "on_command"];
        for name in func_names {
            if let Ok(func) = self
                .instance
                .get_typed_func::<(u32, i64), i32>(&mut self.store, name)
            {
                let res = self.invoke_guest_func(&func, (cmd_hash, arg_len))?;
                return Ok(res == 0);
            }
        }

        Ok(true)
    }

    fn refill_fuel(&mut self) -> ModResult<()> {
        let fuel_limit = self.store.data().config.fuel_per_invocation;
        self.store.set_fuel(fuel_limit).map_err(|e| ModError::Trap {
            mod_id: self.mod_id.clone(),
            message: format!("Failed to set fuel: {e}"),
        })
    }

    fn invoke_guest_func<Params, Results>(
        &mut self,
        func: &TypedFunc<Params, Results>,
        params: Params,
    ) -> ModResult<Results>
    where
        Params: wasmtime::WasmParams,
        Results: wasmtime::WasmResults,
    {
        match func.call(&mut self.store, params) {
            Ok(results) => {
                // Success resets consecutive fault count
                self.store.data_mut().fault_count = 0;
                Ok(results)
            }
            Err(err) => {
                // Check if trap is fuel exhaustion
                let fuel_limit = self.store.data().config.fuel_per_invocation;
                let is_out_of_fuel = err.root_cause().to_string().contains("fuel")
                    || err
                        .downcast_ref::<wasmtime::Trap>()
                        .is_some_and(|t| *t == wasmtime::Trap::OutOfFuel);

                let host_err = if is_out_of_fuel {
                    ModError::FuelExhausted {
                        mod_id: self.mod_id.clone(),
                        fuel_limit,
                    }
                } else {
                    ModError::Trap {
                        mod_id: self.mod_id.clone(),
                        message: err.to_string(),
                    }
                };

                // Track faults
                let state = self.store.data_mut();
                state.fault_count = state.fault_count.saturating_add(1);
                if state.fault_count >= 5 {
                    state.is_suspended = true;
                    tracing::warn!(
                        "Mod '{}' exceeded fault threshold (5 consecutive faults) and has been suspended",
                        self.mod_id
                    );
                }

                Err(host_err)
            }
        }
    }
}
