//! Play phase messages for active in-game communication, chunk streaming, and player replication.

use std::sync::Arc;
use vx_core::coords::ChunkPos;
use vx_voxel::{
    chunk::ChunkSnapshot,
    light::{ChunkLight, LIGHT_LAYER_BYTES, LightLayer},
    occupancy::Occupancy,
    state::BlockStateId,
    storage::{Blocks, Packed},
};

use crate::bounded::{BoundedString, BoundedVec};
use crate::error::{ProtocolError, Result};
use crate::varint::{
    decode_varint, decode_varlong, encode_varint, encode_varlong, unzigzag_i32, zigzag_i32,
};

/// Client responds to server heartbeat challenge to measure RTT.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sKeepAlive {
    /// Opaque challenge ID matching server's keep-alive request.
    pub id: u64,
}

impl C2sKeepAlive {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varlong(cursor)?;
        Ok(Self { id })
    }
}

/// Server issues periodic heartbeat challenge to detect stale connections and measure latency.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cKeepAlive {
    /// Opaque challenge ID generated by server.
    pub id: u64,
}

impl S2cKeepAlive {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varlong(cursor)?;
        Ok(Self { id })
    }
}

/// Client sends chat message or command string to server.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C2sChatMessage {
    /// Message or command payload (max 256 bytes).
    pub message: BoundedString<256>,
}

impl C2sChatMessage {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.message.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let message = BoundedString::<256>::decode(cursor)?;
        Ok(Self { message })
    }
}

/// Server broadcasts formatted chat message or system alert to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cChatMessage {
    /// Sender name or `"[Server]"` prefix.
    pub sender: BoundedString<32>,
    /// Formatted chat message payload.
    pub message: BoundedString<256>,
    /// Millisecond Unix epoch timestamp when message was accepted.
    pub timestamp: u64,
}

impl S2cChatMessage {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.sender.encode(buf);
        self.message.encode(buf);
        encode_varlong(self.timestamp, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sender = BoundedString::<32>::decode(cursor)?;
        let message = BoundedString::<256>::decode(cursor)?;
        let timestamp = decode_varlong(cursor)?;
        Ok(Self {
            sender,
            message,
            timestamp,
        })
    }
}

/// Client notifies server of updated player position and view angles.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct C2sPlayerPosition {
    /// Player world X coordinate.
    pub x: f64,
    /// Player world Y coordinate.
    pub y: f64,
    /// Player world Z coordinate.
    pub z: f64,
    /// Player camera yaw in degrees.
    pub yaw: f32,
    /// Player camera pitch in degrees.
    pub pitch: f32,
    /// Whether player is currently touching ground.
    pub on_ground: bool,
}

impl Eq for C2sPlayerPosition {}

impl C2sPlayerPosition {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&self.x.to_le_bytes());
        buf.extend_from_slice(&self.y.to_le_bytes());
        buf.extend_from_slice(&self.z.to_le_bytes());
        buf.extend_from_slice(&self.yaw.to_le_bytes());
        buf.extend_from_slice(&self.pitch.to_le_bytes());
        buf.push(u8::from(self.on_ground));
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.len() < 33 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let x = f64::from_le_bytes(cursor[0..8].try_into().unwrap());
        let y = f64::from_le_bytes(cursor[8..16].try_into().unwrap());
        let z = f64::from_le_bytes(cursor[16..24].try_into().unwrap());
        let yaw = f32::from_le_bytes(cursor[24..28].try_into().unwrap());
        let pitch = f32::from_le_bytes(cursor[28..32].try_into().unwrap());
        let on_ground = cursor[32] != 0;
        *cursor = &cursor[33..];

        if !x.is_finite() || !y.is_finite() || !z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "position",
                reason: "Coordinates must be finite numbers".to_string(),
            });
        }
        if !yaw.is_finite() || !pitch.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "orientation",
                reason: "Orientation angles must be finite numbers".to_string(),
            });
        }
        if x.abs() > 30_000_000.0 || z.abs() > 30_000_000.0 || !(-2000.0..=5000.0).contains(&y) {
            return Err(ProtocolError::InvalidValue {
                field: "position",
                reason: "Coordinates out of valid world bounds".to_string(),
            });
        }
        if !(-95.0..=95.0).contains(&pitch) {
            return Err(ProtocolError::InvalidValue {
                field: "pitch",
                reason: format!("Pitch angle {pitch} out of valid [-90, 90] range"),
            });
        }

        Ok(Self {
            x,
            y,
            z,
            yaw,
            pitch,
            on_ground,
        })
    }
}

/// Server sends game join confirmation and initial spawn configuration.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct S2cJoinGame {
    /// Server-assigned player entity ID.
    pub entity_id: u32,
    /// Initial spawn position X.
    pub spawn_x: f64,
    /// Initial spawn position Y.
    pub spawn_y: f64,
    /// Initial spawn position Z.
    pub spawn_z: f64,
    /// Server-enforced view distance in chunks.
    pub view_distance: u32,
}

impl Eq for S2cJoinGame {}

impl S2cJoinGame {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.entity_id, buf);
        buf.extend_from_slice(&self.spawn_x.to_le_bytes());
        buf.extend_from_slice(&self.spawn_y.to_le_bytes());
        buf.extend_from_slice(&self.spawn_z.to_le_bytes());
        encode_varint(self.view_distance, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let entity_id = decode_varint(cursor)?;
        if cursor.len() < 24 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let spawn_x = f64::from_le_bytes(cursor[0..8].try_into().unwrap());
        let spawn_y = f64::from_le_bytes(cursor[8..16].try_into().unwrap());
        let spawn_z = f64::from_le_bytes(cursor[16..24].try_into().unwrap());
        *cursor = &cursor[24..];
        let view_distance = decode_varint(cursor)?;

        if !spawn_x.is_finite() || !spawn_y.is_finite() || !spawn_z.is_finite() {
            return Err(ProtocolError::InvalidValue {
                field: "spawn_pos",
                reason: "Spawn coordinates must be finite numbers".to_string(),
            });
        }
        if !(1..=128).contains(&view_distance) {
            return Err(ProtocolError::InvalidValue {
                field: "view_distance",
                reason: format!("View distance {view_distance} out of valid 1..=128 range"),
            });
        }

        Ok(Self {
            entity_id,
            spawn_x,
            spawn_y,
            spawn_z,
            view_distance,
        })
    }
}

/// Serializes an in-memory `ChunkSnapshot` into a compact wire byte representation.
pub fn encode_chunk_snapshot(snapshot: &ChunkSnapshot, buf: &mut Vec<u8>) {
    // 1. Version tag
    buf.push(1);

    // 2. Blocks
    match snapshot.blocks() {
        Blocks::Uniform(state) => {
            buf.push(0);
            encode_varint(state.0, buf);
        }
        Blocks::Packed(packed) => {
            buf.push(1);
            buf.push(packed.log2());
            let palette = packed.palette();
            encode_varint(palette.len() as u32, buf);
            for s in palette {
                encode_varint(s.0, buf);
            }
            let words = packed.words();
            encode_varint(words.len() as u32, buf);
            for w in words {
                buf.extend_from_slice(&w.to_le_bytes());
            }
        }
    }

    // 3. Occupancy
    match snapshot.blocks() {
        Blocks::Uniform(_) => {
            let is_solid = snapshot.occupancy().col_y[0] != 0;
            buf.push(u8::from(is_solid));
        }
        Blocks::Packed(_) => {
            for col in snapshot.occupancy().col_y.iter() {
                buf.extend_from_slice(&col.to_le_bytes());
            }
            for col in snapshot.occupancy().col_x.iter() {
                buf.extend_from_slice(&col.to_le_bytes());
            }
            for col in snapshot.occupancy().col_z.iter() {
                buf.extend_from_slice(&col.to_le_bytes());
            }
        }
    }

    // 4. Light
    if let Some(light) = snapshot.light() {
        buf.push(1);
        match &light.sky {
            LightLayer::Uniform(val) => {
                buf.push(0);
                buf.push(*val);
            }
            LightLayer::Nibbles(bytes) => {
                buf.push(1);
                buf.extend_from_slice(&**bytes);
            }
        }
        match &light.block {
            LightLayer::Uniform(val) => {
                buf.push(0);
                buf.push(*val);
            }
            LightLayer::Nibbles(bytes) => {
                buf.push(1);
                buf.extend_from_slice(&**bytes);
            }
        }
    } else {
        buf.push(0);
    }
}

/// Deserializes a `ChunkSnapshot` from a wire byte slice.
#[allow(clippy::too_many_lines, clippy::similar_names)]
pub fn decode_chunk_snapshot(pos: ChunkPos, cursor: &mut &[u8]) -> Result<ChunkSnapshot> {
    if cursor.is_empty() {
        return Err(ProtocolError::UnexpectedEof);
    }
    let version = cursor[0];
    *cursor = &cursor[1..];
    if version != 1 {
        return Err(ProtocolError::Malformed(format!(
            "Unsupported chunk snapshot codec version: {version}"
        )));
    }

    // Blocks
    if cursor.is_empty() {
        return Err(ProtocolError::UnexpectedEof);
    }
    let blocks_tag = cursor[0];
    *cursor = &cursor[1..];

    let (blocks, is_uniform) = match blocks_tag {
        0 => {
            let state_id = decode_varint(cursor)?;
            (Blocks::Uniform(BlockStateId(state_id)), true)
        }
        1 => {
            if cursor.is_empty() {
                return Err(ProtocolError::UnexpectedEof);
            }
            let log2 = cursor[0];
            *cursor = &cursor[1..];
            if log2 > 4 {
                return Err(ProtocolError::Malformed(format!(
                    "Invalid log2 bit width: {log2}"
                )));
            }

            let palette_len = decode_varint(cursor)? as usize;
            let mut palette = Vec::with_capacity(palette_len);
            for _ in 0..palette_len {
                let id = decode_varint(cursor)?;
                palette.push(BlockStateId(id));
            }

            let words_len = decode_varint(cursor)? as usize;
            let expected_words = 512usize << log2;
            if words_len != expected_words {
                return Err(ProtocolError::Malformed(format!(
                    "Words length mismatch: got {words_len}, expected {expected_words}"
                )));
            }

            let required_bytes = words_len * 8;
            if cursor.len() < required_bytes {
                return Err(ProtocolError::UnexpectedEof);
            }

            let mut words = Vec::with_capacity(words_len);
            for _ in 0..words_len {
                let w = u64::from_le_bytes(cursor[..8].try_into().unwrap());
                *cursor = &cursor[8..];
                words.push(w);
            }

            let packed =
                Packed::from_raw_parts(log2, palette.into_boxed_slice(), words.into_boxed_slice());
            (Blocks::Packed(Box::new(packed)), false)
        }
        tag => {
            return Err(ProtocolError::Malformed(format!(
                "Invalid blocks tag: {tag}"
            )));
        }
    };

    // Occupancy
    let occupancy = if is_uniform {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let is_solid = cursor[0] != 0;
        *cursor = &cursor[1..];
        if is_solid {
            Occupancy::solid()
        } else {
            Occupancy::empty()
        }
    } else {
        if cursor.len() < 12288 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let mut col_y = vec![0u32; 1024];
        for item in &mut col_y {
            *item = u32::from_le_bytes(cursor[..4].try_into().unwrap());
            *cursor = &cursor[4..];
        }
        let mut col_x = vec![0u32; 1024];
        for item in &mut col_x {
            *item = u32::from_le_bytes(cursor[..4].try_into().unwrap());
            *cursor = &cursor[4..];
        }
        let mut col_z = vec![0u32; 1024];
        for item in &mut col_z {
            *item = u32::from_le_bytes(cursor[..4].try_into().unwrap());
            *cursor = &cursor[4..];
        }
        Occupancy {
            col_y: col_y.into_boxed_slice().try_into().unwrap(),
            col_x: col_x.into_boxed_slice().try_into().unwrap(),
            col_z: col_z.into_boxed_slice().try_into().unwrap(),
        }
    };

    // Light
    if cursor.is_empty() {
        return Err(ProtocolError::UnexpectedEof);
    }
    let light_tag = cursor[0];
    *cursor = &cursor[1..];

    let light = match light_tag {
        0 => None,
        1 => {
            if cursor.is_empty() {
                return Err(ProtocolError::UnexpectedEof);
            }
            let sky_tag = cursor[0];
            *cursor = &cursor[1..];
            let sky = match sky_tag {
                0 => {
                    if cursor.is_empty() {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let val = cursor[0];
                    *cursor = &cursor[1..];
                    LightLayer::Uniform(val)
                }
                1 => {
                    if cursor.len() < LIGHT_LAYER_BYTES {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let mut bytes = Box::new([0u8; LIGHT_LAYER_BYTES]);
                    bytes.copy_from_slice(&cursor[..LIGHT_LAYER_BYTES]);
                    *cursor = &cursor[LIGHT_LAYER_BYTES..];
                    LightLayer::Nibbles(bytes)
                }
                tag => {
                    return Err(ProtocolError::Malformed(format!(
                        "Invalid sky light tag: {tag}"
                    )));
                }
            };

            if cursor.is_empty() {
                return Err(ProtocolError::UnexpectedEof);
            }
            let block_tag = cursor[0];
            *cursor = &cursor[1..];
            let block = match block_tag {
                0 => {
                    if cursor.is_empty() {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let val = cursor[0];
                    *cursor = &cursor[1..];
                    LightLayer::Uniform(val)
                }
                1 => {
                    if cursor.len() < LIGHT_LAYER_BYTES {
                        return Err(ProtocolError::UnexpectedEof);
                    }
                    let mut bytes = Box::new([0u8; LIGHT_LAYER_BYTES]);
                    bytes.copy_from_slice(&cursor[..LIGHT_LAYER_BYTES]);
                    *cursor = &cursor[LIGHT_LAYER_BYTES..];
                    LightLayer::Nibbles(bytes)
                }
                tag => {
                    return Err(ProtocolError::Malformed(format!(
                        "Invalid block light tag: {tag}"
                    )));
                }
            };

            Some(ChunkLight { sky, block })
        }
        tag => {
            return Err(ProtocolError::Malformed(format!(
                "Invalid light tag: {tag}"
            )));
        }
    };

    Ok(ChunkSnapshot::from_parts(
        pos, blocks, occupancy, light, 0, [0; 6], 0,
    ))
}

/// Chunk data payload carrier supporting zero-copy in-memory snapshots and bounded wire bytes.
#[derive(Debug, Clone)]
pub enum ChunkPayload {
    /// Zero-copy snapshot reference for in-process singleplayer transport.
    Snapshot(Arc<ChunkSnapshot>),
    /// Serialized byte buffer for network transport.
    Wire(BoundedVec<u8, 262_144>),
}

impl ChunkPayload {
    /// Resolves or decodes this payload into an `Arc<ChunkSnapshot>`.
    pub fn to_snapshot(&self, pos: ChunkPos) -> Result<Arc<ChunkSnapshot>> {
        match self {
            Self::Snapshot(snap) => Ok(snap.clone()),
            Self::Wire(wire) => {
                let mut cursor = wire.as_slice();
                let snap = decode_chunk_snapshot(pos, &mut cursor)?;
                Ok(Arc::new(snap))
            }
        }
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Snapshot(snap) => {
                let mut wire_bytes = Vec::new();
                encode_chunk_snapshot(snap, &mut wire_bytes);
                let bounded = BoundedVec::<u8, 262_144>::new(wire_bytes)
                    .expect("Chunk snapshot serialization exceeded 262 KiB limit");
                bounded.encode(buf);
            }
            Self::Wire(wire) => {
                wire.encode(buf);
            }
        }
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let wire = BoundedVec::<u8, 262_144>::decode(cursor)?;
        Ok(Self::Wire(wire))
    }
}

impl PartialEq for ChunkPayload {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Snapshot(a), Self::Snapshot(b)) => {
                Arc::ptr_eq(a, b)
                    || (a.position() == b.position()
                        && a.blocks() == b.blocks()
                        && a.light() == b.light())
            }
            (Self::Wire(a), Self::Wire(b)) => a == b,
            _ => false,
        }
    }
}

impl Eq for ChunkPayload {}

/// Server sends chunk voxel and light data to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cChunkData {
    /// Chunk coordinate X.
    pub chunk_x: i32,
    /// Chunk coordinate Y.
    pub chunk_y: i32,
    /// Chunk coordinate Z.
    pub chunk_z: i32,
    /// Chunk content mutation version.
    pub version: u32,
    /// Server world epoch tick counter.
    pub epoch: u32,
    /// Chunk payload (snapshot or wire bytes).
    pub payload: ChunkPayload,
}

impl S2cChunkData {
    /// Grid position of this chunk.
    #[must_use]
    pub const fn pos(&self) -> ChunkPos {
        ChunkPos::new(self.chunk_x, self.chunk_y, self.chunk_z)
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.chunk_x), buf);
        encode_varint(zigzag_i32(self.chunk_y), buf);
        encode_varint(zigzag_i32(self.chunk_z), buf);
        encode_varint(self.version, buf);
        encode_varint(self.epoch, buf);
        self.payload.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let chunk_x = unzigzag_i32(decode_varint(cursor)?);
        let chunk_y = unzigzag_i32(decode_varint(cursor)?);
        let chunk_z = unzigzag_i32(decode_varint(cursor)?);
        let version = decode_varint(cursor)?;
        let epoch = decode_varint(cursor)?;
        let payload = ChunkPayload::decode(cursor)?;

        if chunk_x.abs() > 1_000_000
            || chunk_z.abs() > 1_000_000
            || !(-100..=200).contains(&chunk_y)
        {
            return Err(ProtocolError::InvalidValue {
                field: "chunk_pos",
                reason: "Chunk coordinates out of allowable world bounds".to_string(),
            });
        }

        Ok(Self {
            chunk_x,
            chunk_y,
            chunk_z,
            version,
            epoch,
            payload,
        })
    }
}

/// Server sends lightweight uniform chunk descriptor (0-byte payload elision).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cUniformChunk {
    /// Chunk coordinate X.
    pub chunk_x: i32,
    /// Chunk coordinate Y.
    pub chunk_y: i32,
    /// Chunk coordinate Z.
    pub chunk_z: i32,
    /// Chunk content mutation version.
    pub version: u32,
    /// Uniform block state throughout chunk.
    pub block_state: BlockStateId,
    /// Uniform sky light level (0..=15).
    pub sky_light: u8,
    /// Uniform block light level (0..=15).
    pub block_light: u8,
}

impl S2cUniformChunk {
    /// Grid position of this chunk.
    #[must_use]
    pub const fn pos(&self) -> ChunkPos {
        ChunkPos::new(self.chunk_x, self.chunk_y, self.chunk_z)
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.chunk_x), buf);
        encode_varint(zigzag_i32(self.chunk_y), buf);
        encode_varint(zigzag_i32(self.chunk_z), buf);
        encode_varint(self.version, buf);
        encode_varint(self.block_state.0, buf);
        buf.push(self.sky_light);
        buf.push(self.block_light);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let chunk_x = unzigzag_i32(decode_varint(cursor)?);
        let chunk_y = unzigzag_i32(decode_varint(cursor)?);
        let chunk_z = unzigzag_i32(decode_varint(cursor)?);
        let version = decode_varint(cursor)?;
        let block_state = BlockStateId(decode_varint(cursor)?);
        if cursor.len() < 2 {
            return Err(ProtocolError::UnexpectedEof);
        }
        let sky_light = cursor[0];
        let block_light = cursor[1];
        *cursor = &cursor[2..];

        if chunk_x.abs() > 1_000_000
            || chunk_z.abs() > 1_000_000
            || !(-100..=200).contains(&chunk_y)
        {
            return Err(ProtocolError::InvalidValue {
                field: "chunk_pos",
                reason: "Chunk coordinates out of allowable world bounds".to_string(),
            });
        }
        if sky_light > 15 || block_light > 15 {
            return Err(ProtocolError::InvalidValue {
                field: "light",
                reason: format!(
                    "Light level out of range 0..=15: sky={sky_light}, block={block_light}"
                ),
            });
        }

        Ok(Self {
            chunk_x,
            chunk_y,
            chunk_z,
            version,
            block_state,
            sky_light,
            block_light,
        })
    }

    /// Converts this uniform chunk into a `ChunkSnapshot`.
    #[must_use]
    pub fn to_snapshot(&self, is_opaque: bool) -> ChunkSnapshot {
        let light = ChunkLight {
            sky: LightLayer::uniform(self.sky_light),
            block: LightLayer::uniform(self.block_light),
        };
        ChunkSnapshot::new_uniform(self.pos(), self.block_state, is_opaque, Some(light))
    }
}

/// Server notifies client to evict chunk outside view distance.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cChunkUnload {
    /// Chunk coordinate X.
    pub chunk_x: i32,
    /// Chunk coordinate Y.
    pub chunk_y: i32,
    /// Chunk coordinate Z.
    pub chunk_z: i32,
}

impl S2cChunkUnload {
    /// Grid position of this chunk.
    #[must_use]
    pub const fn pos(&self) -> ChunkPos {
        ChunkPos::new(self.chunk_x, self.chunk_y, self.chunk_z)
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.chunk_x), buf);
        encode_varint(zigzag_i32(self.chunk_y), buf);
        encode_varint(zigzag_i32(self.chunk_z), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let chunk_x = unzigzag_i32(decode_varint(cursor)?);
        let chunk_y = unzigzag_i32(decode_varint(cursor)?);
        let chunk_z = unzigzag_i32(decode_varint(cursor)?);

        if chunk_x.abs() > 1_000_000
            || chunk_z.abs() > 1_000_000
            || !(-100..=200).contains(&chunk_y)
        {
            return Err(ProtocolError::InvalidValue {
                field: "chunk_pos",
                reason: "Chunk coordinates out of allowable world bounds".to_string(),
            });
        }

        Ok(Self {
            chunk_x,
            chunk_y,
            chunk_z,
        })
    }
}

/// LOD node payload carrier supporting zero-copy in-memory buffers and bounded wire bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LodPayload {
    /// Zero-copy buffer reference for in-process singleplayer transport.
    Memory(Arc<Vec<u32>>),
    /// Serialized byte buffer for network transport.
    Wire(BoundedVec<u8, 262_144>),
}

impl LodPayload {
    /// Extracts the underlying `u32` words from the payload.
    #[must_use]
    pub fn to_words(&self) -> Vec<u32> {
        match self {
            Self::Memory(vec) => (**vec).clone(),
            Self::Wire(wire) => {
                let bytes = wire.as_slice();
                let (chunks, _) = bytes.as_chunks::<4>();
                let mut words = Vec::with_capacity(chunks.len());
                for chunk in chunks {
                    words.push(u32::from_le_bytes(*chunk));
                }
                words
            }
        }
    }

    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Memory(vec) => {
                let byte_len = vec.len() * 4;
                let mut wire_bytes = Vec::with_capacity(byte_len);
                for w in vec.iter() {
                    wire_bytes.extend_from_slice(&w.to_le_bytes());
                }
                let bounded = BoundedVec::<u8, 262_144>::new(wire_bytes)
                    .expect("LOD mesh serialization exceeded 262 KiB limit");
                bounded.encode(buf);
            }
            Self::Wire(wire) => {
                wire.encode(buf);
            }
        }
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let wire = BoundedVec::<u8, 262_144>::decode(cursor)?;
        Ok(Self::Wire(wire))
    }
}

/// Server sends greedy-meshed LOD node geometry and palette to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cLodNodeData {
    /// Clipmap hierarchy level (L >= 1).
    pub level: u8,
    /// Node coordinate X in level-L grid.
    pub node_x: i32,
    /// Node coordinate Y in level-L grid.
    pub node_y: i32,
    /// Node coordinate Z in level-L grid.
    pub node_z: i32,
    /// Content version for eviction/replacement tracking.
    pub version: u64,
    /// Number of 8-byte quads packed in payload.
    pub quad_count: u32,
    /// Number of RGBA8 palette entries trailing quads in payload.
    pub palette_count: u32,
    /// LOD payload (quads + palette as u32 words).
    pub payload: LodPayload,
}

impl S2cLodNodeData {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.push(self.level);
        encode_varint(zigzag_i32(self.node_x), buf);
        encode_varint(zigzag_i32(self.node_y), buf);
        encode_varint(zigzag_i32(self.node_z), buf);
        encode_varlong(self.version, buf);
        encode_varint(self.quad_count, buf);
        encode_varint(self.palette_count, buf);
        self.payload.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let level = cursor[0];
        *cursor = &cursor[1..];
        let node_x = unzigzag_i32(decode_varint(cursor)?);
        let node_y = unzigzag_i32(decode_varint(cursor)?);
        let node_z = unzigzag_i32(decode_varint(cursor)?);
        let version = decode_varlong(cursor)?;
        let quad_count = decode_varint(cursor)?;
        let palette_count = decode_varint(cursor)?;
        let payload = LodPayload::decode(cursor)?;

        if !(1..=16).contains(&level) {
            return Err(ProtocolError::InvalidValue {
                field: "level",
                reason: format!("LOD level {level} out of range 1..=16"),
            });
        }
        if node_x.abs() > 1_000_000 || node_z.abs() > 1_000_000 || !(-100..=200).contains(&node_y) {
            return Err(ProtocolError::InvalidValue {
                field: "node_pos",
                reason: "LOD node coordinates out of bounds".to_string(),
            });
        }

        Ok(Self {
            level,
            node_x,
            node_y,
            node_z,
            version,
            quad_count,
            palette_count,
            payload,
        })
    }
}

/// Server instructs client to evict LOD node outside view distance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct S2cLodNodeUnload {
    /// Clipmap hierarchy level (L >= 1).
    pub level: u8,
    /// Node coordinate X in level-L grid.
    pub node_x: i32,
    /// Node coordinate Y in level-L grid.
    pub node_y: i32,
    /// Node coordinate Z in level-L grid.
    pub node_z: i32,
}

impl S2cLodNodeUnload {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        buf.push(self.level);
        encode_varint(zigzag_i32(self.node_x), buf);
        encode_varint(zigzag_i32(self.node_y), buf);
        encode_varint(zigzag_i32(self.node_z), buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let level = cursor[0];
        *cursor = &cursor[1..];
        let node_x = unzigzag_i32(decode_varint(cursor)?);
        let node_y = unzigzag_i32(decode_varint(cursor)?);
        let node_z = unzigzag_i32(decode_varint(cursor)?);

        if !(1..=16).contains(&level) {
            return Err(ProtocolError::InvalidValue {
                field: "level",
                reason: format!("LOD level {level} out of range 1..=16"),
            });
        }
        if node_x.abs() > 1_000_000 || node_z.abs() > 1_000_000 || !(-100..=200).contains(&node_y) {
            return Err(ProtocolError::InvalidValue {
                field: "node_pos",
                reason: "LOD node coordinates out of bounds".to_string(),
            });
        }

        Ok(Self {
            level,
            node_x,
            node_y,
            node_z,
        })
    }
}

/// Kind of block action initiated by client.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockActionKind {
    /// Destroy the targeted block.
    Break,
    /// Place a block against the targeted face.
    Place {
        /// Target block state to place.
        state_id: BlockStateId,
        /// Face index against which the block was placed.
        hit_face: u8,
    },
}

impl BlockActionKind {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Break => buf.push(0),
            Self::Place { state_id, hit_face } => {
                buf.push(1);
                encode_varint(state_id.as_u32(), buf);
                buf.push(*hit_face);
            }
        }
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        if cursor.is_empty() {
            return Err(ProtocolError::UnexpectedEof);
        }
        let kind = cursor[0];
        *cursor = &cursor[1..];
        match kind {
            0 => Ok(Self::Break),
            1 => {
                let state_id = BlockStateId::new(decode_varint(cursor)?);
                if cursor.is_empty() {
                    return Err(ProtocolError::UnexpectedEof);
                }
                let hit_face = cursor[0];
                if hit_face > 5 {
                    return Err(ProtocolError::InvalidValue {
                        field: "hit_face",
                        reason: format!("Hit face {hit_face} out of valid range 0..=5"),
                    });
                }
                *cursor = &cursor[1..];
                Ok(Self::Place { state_id, hit_face })
            }
            other => Err(ProtocolError::Malformed(format!(
                "Unknown block action kind {other}"
            ))),
        }
    }
}

/// Client sends block break or place action to server.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sBlockAction {
    /// Monotonically increasing sequence number for prediction reconciliation.
    pub sequence: u32,
    /// Action kind: break or place.
    pub action: BlockActionKind,
    /// World block X coordinate.
    pub x: i32,
    /// World block Y coordinate.
    pub y: i32,
    /// World block Z coordinate.
    pub z: i32,
    /// Client simulation tick at the moment the action was triggered.
    pub input_tick: u32,
}

impl C2sBlockAction {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.sequence, buf);
        self.action.encode(buf);
        encode_varint(zigzag_i32(self.x), buf);
        encode_varint(zigzag_i32(self.y), buf);
        encode_varint(zigzag_i32(self.z), buf);
        encode_varint(self.input_tick, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sequence = decode_varint(cursor)?;
        let action = BlockActionKind::decode(cursor)?;
        let x = unzigzag_i32(decode_varint(cursor)?);
        let y = unzigzag_i32(decode_varint(cursor)?);
        let z = unzigzag_i32(decode_varint(cursor)?);
        let input_tick = decode_varint(cursor)?;

        if x.abs() > 30_000_000 || z.abs() > 30_000_000 || !(-2000..=5000).contains(&y) {
            return Err(ProtocolError::InvalidValue {
                field: "block_pos",
                reason: "Block coordinates out of world bounds".to_string(),
            });
        }

        Ok(Self {
            sequence,
            action,
            x,
            y,
            z,
            input_tick,
        })
    }
}

/// Server notifies client of an updated block state in the world.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cBlockUpdate {
    /// World block X coordinate.
    pub x: i32,
    /// World block Y coordinate.
    pub y: i32,
    /// World block Z coordinate.
    pub z: i32,
    /// Updated block state ID.
    pub state_id: BlockStateId,
    /// Chunk content version.
    pub version: u64,
}

impl S2cBlockUpdate {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(zigzag_i32(self.x), buf);
        encode_varint(zigzag_i32(self.y), buf);
        encode_varint(zigzag_i32(self.z), buf);
        encode_varint(self.state_id.as_u32(), buf);
        encode_varlong(self.version, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let x = unzigzag_i32(decode_varint(cursor)?);
        let y = unzigzag_i32(decode_varint(cursor)?);
        let z = unzigzag_i32(decode_varint(cursor)?);
        let state_id = BlockStateId::new(decode_varint(cursor)?);
        let version = decode_varlong(cursor)?;

        if x.abs() > 30_000_000 || z.abs() > 30_000_000 || !(-2000..=5000).contains(&y) {
            return Err(ProtocolError::InvalidValue {
                field: "block_pos",
                reason: "Block coordinates out of world bounds".to_string(),
            });
        }

        Ok(Self {
            x,
            y,
            z,
            state_id,
            version,
        })
    }
}

/// Server acknowledges client predicted block actions up to a given sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cBlockActionAck {
    /// Highest acknowledged action sequence number.
    pub sequence: u32,
}

impl S2cBlockActionAck {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varint(self.sequence, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sequence = decode_varint(cursor)?;
        Ok(Self { sequence })
    }
}

/// Server synchronizes world age and time of day to clients.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cUpdateTime {
    /// Total ticks elapsed in the world since generation.
    pub world_age: u64,
    /// Current time of day in ticks (0..24000).
    pub time_of_day: u64,
}

impl S2cUpdateTime {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.world_age, buf);
        encode_varlong(self.time_of_day, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let world_age = decode_varlong(cursor)?;
        let time_of_day = decode_varlong(cursor)?;
        Ok(Self {
            world_age,
            time_of_day,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_update_time_codec_round_trip() {
        let msg = S2cUpdateTime {
            world_age: 144_000,
            time_of_day: 6_000,
        };
        let mut buf = Vec::new();
        msg.encode(&mut buf);

        let mut cursor = &buf[..];
        let decoded = S2cUpdateTime::decode(&mut cursor).expect("failed to decode S2cUpdateTime");
        assert_eq!(msg, decoded);
        assert!(cursor.is_empty());
    }
}
