//! Play phase messages for active in-game communication and heartbeats.

use crate::bounded::BoundedString;
use crate::error::Result;
use crate::varint::{decode_varlong, encode_varlong};

/// Client responds to server heartbeat challenge to measure RTT.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2sKeepAlive {
    /// Opaque challenge ID matching server's keep-alive request.
    pub id: u64,
}

impl C2sKeepAlive {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varlong(cursor)?;
        Ok(Self { id })
    }
}

/// Server issues periodic heartbeat challenge to detect stale connections and measure latency.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct S2cKeepAlive {
    /// Opaque challenge ID generated by server.
    pub id: u64,
}

impl S2cKeepAlive {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        encode_varlong(self.id, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let id = decode_varlong(cursor)?;
        Ok(Self { id })
    }
}

/// Client sends chat message or command string to server.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C2sChatMessage {
    /// Message or command payload (max 256 bytes).
    pub message: BoundedString<256>,
}

impl C2sChatMessage {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.message.encode(buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let message = BoundedString::<256>::decode(cursor)?;
        Ok(Self { message })
    }
}

/// Server broadcasts formatted chat message or system alert to client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct S2cChatMessage {
    /// Sender name or `"[Server]"` prefix.
    pub sender: BoundedString<32>,
    /// Formatted chat message payload.
    pub message: BoundedString<256>,
    /// Millisecond Unix epoch timestamp when message was accepted.
    pub timestamp: u64,
}

impl S2cChatMessage {
    /// Encodes into wire buffer.
    pub fn encode(&self, buf: &mut Vec<u8>) {
        self.sender.encode(buf);
        self.message.encode(buf);
        encode_varlong(self.timestamp, buf);
    }

    /// Decodes from wire buffer.
    pub fn decode(cursor: &mut &[u8]) -> Result<Self> {
        let sender = BoundedString::<32>::decode(cursor)?;
        let message = BoundedString::<256>::decode(cursor)?;
        let timestamp = decode_varlong(cursor)?;
        Ok(Self {
            sender,
            message,
            timestamp,
        })
    }
}
